# **Data Cleaning**

In [1]:
import pandas as pd
from pathlib import Path

def load_excel(file_path):
    file_ext = Path(file_path).suffix.lower()

    if file_ext == ".xlsx":
        return pd.read_excel(file_path, engine="openpyxl", header=1)

    elif file_ext == ".xls":
        return pd.read_excel(file_path, engine="xlrd")

    else:
        raise ValueError("Unsupported file format. Use .xls or .xlsx")

In [2]:
# Load two files
df1 = load_excel(r"C:\Users\subra\OneDrive\Inward Register Feb-25.xlsx")
df2 = pd.read_excel(
    r"C:\Users\subra\OneDrive\022025_29ADAFS3950J1ZS_GSTR2B_18032025_SSA Firm.xlsx",
    sheet_name="B2B",
    engine="openpyxl",
    header = [4,5]
)
print(df1.head())
print(df2.head())

       Accounting Date      Month    Nature         Type  \
0  2025-02-01 00:00:00 2025-02-01  Eligible  Intra-state
1  2025-02-04 00:00:00 2025-02-04  Eligible  Intra-state
2  2025-02-01 00:00:00 2025-02-01  Eligible  Intra-state
3  2025-02-01 00:00:00 2025-02-01  Eligible  Intra-state
4  2025-02-01 00:00:00 2025-02-01  Eligible  Intra-state

                     Supplier        GSTIN/UIN                  Supplier.1  \
0              NK Enterprises              NaN              NK Enterprises
1                  Sona Roopa  29AACHS2083M1ZO                  Sona Roopa
2              Akshaya Groups  29GYXPS5110J1ZJ              Akshaya Groups
3  SapanaPlywood and Hardware  29HGDPS9329Q1Z4  SapanaPlywood and Hardware
4         Shri Ganesh Traders  29AEUPD9813N1ZM         Shri Ganesh Traders

  Voucher Type  Voucher Number  Gross Total  ...  Taxable @ 28%  Others  \
0          NaN             NaN   14999.9948  ...            0.0     0.0
1     Purchase            8012   16799.9904  ...            0.0     0.0
2     Purchase   AK24-25/00872   11446.0000  ...            0.0     0.0
3     Purchase             351   47811.2400  ...            0.0     0.0
4     Purchase  SGT/23-24/8837     899.7500  ...            0.0     0.0

   Taxable Value       CGST       SGST  IGST Cess  \
0       12711.86  1144.0674  1144.0674   0.0  0.0
1       14237.28  1281.3552  1281.3552   0.0  0.0
2           9700   873.0000   873.0000   0.0  0.0
3          40518  3646.6200  3646.6200   0.0  0.0
4          762.5    68.6250    68.6250   0.0  0.0

        Description as per tally  \
0  Printing & Stationery A/c 18%
1  Printing & Stationery A/c 18%
2        Material Purchase @ 18%
3        Material Purchase @ 18%
4        Material Purchase @ 18%

                                  Actual description     %
0  Being TK 1178 OG (Toner Cartridge) -Black Cart...  0.18
1                  Being , Site Stationery Purchased  0.18
2  Being Gift -Set, 3 in 1 giftset, Branding charges  0.18
3  Being  Marine plywood 19mm(4x7) , Lam -9015 SO...  0.18
4  Being  Cutting Wheel 4"  ,site Material purchased  0.18

[5 rows x 24 columns]
   GSTIN of supplier                     Trade/Legal name Invoice Details  \
  Unnamed: 0_level_1                   Unnamed: 1_level_1  Invoice number
0    33AABCV3609C1ZU                VRL LOGISTICS LIMITED      2693198910
1    33AABCV3609C1ZU                VRL LOGISTICS LIMITED      3247580610
2    29ADKPP9487H1ZL                     MAHESH HARDWARES            3264
3    29AAZPN5768K1ZF  SHRI SHANTESHWAR ENGINERING COMPNAY  SSE/2079/24-25
4    29AAOFH3996A1Z0          HITECH ENGINEERING SERVICES        B2BS-164

                                                Place of supply  \
  Invoice type Invoice Date Invoice Value(₹) Unnamed: 6_level_1
0      Regular   06/02/2025           2890.0          Karnataka
1      Regular   15/02/2025            490.0          Karnataka
2      Regular   18/02/2025           1300.0          Karnataka
3      Regular   17/02/2025            750.0          Karnataka
4      Regular   08/02/2025           8260.0          Karnataka

  Supply Attract Reverse Charge  Taxable Value (₹)        Tax Amount  ...  \
             Unnamed: 7_level_1 Unnamed: 8_level_1 Integrated Tax(₹)  ...
0                           Yes            2890.00             144.5  ...
1                           Yes             490.00              24.5  ...
2                            No            1101.70               0.0  ...
3                            No             635.59               0.0  ...
4                            No            7000.00               0.0  ...

                          GSTR-1/IFF/GSTR-5 Period  \
  State/UT Tax(₹) Cess(₹)      Unnamed: 13_level_1
0            0.00       0                   Feb'25
1            0.00       0                   Feb'25
2           99.15       0                   Feb'25
3           57.20       0                   Feb'25
4          630.00       0                   Feb'25

  GSTR-1/IFF/GSTR-5 Filing Date    ITC Availability              Reason  \
            Unnamed: 14_level_1 Unnamed: 15_level_1 Unnamed: 16_level_1
0                    11/03/2025                 Yes                 NaN
1                    11/03/2025                 Yes                 NaN
2                    09/03/2025                 Yes                 NaN
3                    11/03/2025                 Yes                 NaN
4                    11/03/2025                 Yes                 NaN

  Applicable % of Tax Rate              Source  \
       Unnamed: 17_level_1 Unnamed: 18_level_1
0                     100%                 NaN
1                     100%                 NaN
2                     100%                 NaN
3                     100%           E-Invoice
4                     100%           E-Invoice

                                                 IRN            IRN Date
                                 Unnamed: 19_level_1 Unnamed: 20_level_1
0                                                NaN                 NaN
1                                                NaN                 NaN
2                                                NaN                 NaN
3  35b64dae4bd14d18f58b09cf1298d5f26d65e79eb77a57...          24/02/2025
4  593070c2921bdf2e9dfe6a003e4946c51513b00d4cedc8...          08/02/2025

[5 rows x 21 columns]

In [3]:
df1

,Accounting Date,Month,Nature,Type,Supplier,GSTIN/UIN,Supplier.1,Voucher Type,Voucher Number,Gross Total,...,Taxable @ 28%,Others,Taxable Value,CGST,SGST,IGST,Cess,Description as per tally,Actual description,%
0,2025-02-01 00:00:00,2025-02-01,Eligible,Intra-state,NK Enterprises,NaN,NK Enterprises,NaN,NaN,14999.9948,...,0.0,0.0,12711.86,1.144067e+03,1.144067e+03,0.000000e+00,0.0,Printing & Stationery A/c 18%,Being TK 1178 OG (Toner Cartridge) -Black Cart...,0.18
1,2025-02-04 00:00:00,2025-02-04,Eligible,Intra-state,Sona Roopa,29AACHS2083M1ZO,Sona Roopa,Purchase,8012,16799.9904,...,0.0,0.0,14237.28,1.281355e+03,1.281355e+03,0.000000e+00,0.0,Printing & Stationery A/c 18%,"Being , Site Stationery Purchased",0.18
2,2025-02-01 00:00:00,2025-02-01,Eligible,Intra-state,Akshaya Groups,29GYXPS5110J1ZJ,Akshaya Groups,Purchase,AK24-25/00872,11446.0000,...,0.0,0.0,9700,8.730000e+02,8.730000e+02,0.000000e+00,0.0,Material Purchase @ 18%,"Being Gift -Set, 3 in 1 giftset, Branding charges",0.18
3,2025-02-01 00:00:00,2025-02-01,Eligible,Intra-state,SapanaPlywood and Hardware,29HGDPS9329Q1Z4,SapanaPlywood and Hardware,Purchase,351,47811.2400,...,0.0,0.0,40518,3.646620e+03,3.646620e+03,0.000000e+00,0.0,Material Purchase @ 18%,"Being Marine plywood 19mm(4x7) , Lam -9015 SO...",0.18
4,2025-02-01 00:00:00,2025-02-01,Eligible,Intra-state,Shri Ganesh Traders,29AEUPD9813N1ZM,Shri Ganesh Traders,Purchase,SGT/23-24/8837,899.7500,...,0.0,0.0,762.5,6.862500e+01,6.862500e+01,0.000000e+00,0.0,Material Purchase @ 18%,"Being Cutting Wheel 4"" ,site Material purchased",0.18
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
591,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
592,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
593,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,As per Tally,5.968014e+06,5.968014e+06,1.448632e+06,NaN,NaN,NaN,NaN
594,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,As per Workings,5.968013e+06,5.968013e+06,1.448632e+06,NaN,NaN,NaN,NaN
595,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,Difference,9.903000e-01,9.903000e-01,-1.220000e-02,NaN,NaN,NaN,NaN

In [4]:
df2

     GSTIN of supplier                     Trade/Legal name   Invoice Details  \
    Unnamed: 0_level_1                   Unnamed: 1_level_1    Invoice number
0      33AABCV3609C1ZU                VRL LOGISTICS LIMITED        2693198910
1      33AABCV3609C1ZU                VRL LOGISTICS LIMITED        3247580610
2      29ADKPP9487H1ZL                     MAHESH HARDWARES              3264
3      29AAZPN5768K1ZF  SHRI SHANTESHWAR ENGINERING COMPNAY    SSE/2079/24-25
4      29AAOFH3996A1Z0          HITECH ENGINEERING SERVICES          B2BS-164
..                 ...                                  ...               ...
460    29ANCPP7008E1Z1                  PRAKASH ELECTRICALS     PE/24-25/4292
461    29ADBFS3634C1Z9                SEPL STEEL AND CEMENT  SCHPT/24-25/1371
462    29ADBFS3634C1Z9                SEPL STEEL AND CEMENT  SCHPT/24-25/1372
463    29ADBFS3634C1Z9                SEPL STEEL AND CEMENT  SCHPT/24-25/1385
464    29ADBFS3634C1Z9                SEPL STEEL AND CEMENT  SCHPT/24-25/1386

                                                  Place of supply  \
    Invoice type Invoice Date Invoice Value(₹) Unnamed: 6_level_1
0        Regular   06/02/2025           2890.0          Karnataka
1        Regular   15/02/2025            490.0          Karnataka
2        Regular   18/02/2025           1300.0          Karnataka
3        Regular   17/02/2025            750.0          Karnataka
4        Regular   08/02/2025           8260.0          Karnataka
..           ...          ...              ...                ...
460      Regular   24/02/2025           4311.0          Karnataka
461      Regular   03/02/2025        1931117.0          Karnataka
462      Regular   03/02/2025         556063.0          Karnataka
463      Regular   10/02/2025        2257600.0          Karnataka
464      Regular   10/02/2025         493948.0          Karnataka

    Supply Attract Reverse Charge  Taxable Value (₹)        Tax Amount  ...  \
               Unnamed: 7_level_1 Unnamed: 8_level_1 Integrated Tax(₹)  ...
0                             Yes            2890.00             144.5  ...
1                             Yes             490.00              24.5  ...
2                              No            1101.70               0.0  ...
3                              No             635.59               0.0  ...
4                              No            7000.00               0.0  ...
..                            ...                ...               ...  ...
460                            No            3653.40               0.0  ...
461                            No         1636540.00               0.0  ...
462                            No          471240.00               0.0  ...
463                            No         1913220.00               0.0  ...
464                            No          418600.00               0.0  ...

                            GSTR-1/IFF/GSTR-5 Period  \
    State/UT Tax(₹) Cess(₹)      Unnamed: 13_level_1
0              0.00       0                   Feb'25
1              0.00       0                   Feb'25
2             99.15       0                   Feb'25
3             57.20       0                   Feb'25
4            630.00       0                   Feb'25
..              ...     ...                      ...
460          328.81       0                   Feb'25
461       147288.60       0                   Feb'25
462        42411.60       0                   Feb'25
463       172189.80       0                   Feb'25
464        37674.00       0                   Feb'25

    GSTR-1/IFF/GSTR-5 Filing Date    ITC Availability              Reason  \
              Unnamed: 14_level_1 Unnamed: 15_level_1 Unnamed: 16_level_1
0                      11/03/2025                 Yes                 NaN
1                      11/03/2025                 Yes                 NaN
2                      09/03/2025                 Yes                 NaN
3                      11/03/2025                 Yes                 NaN
4                      11/03/2025                 Yes                 NaN
..                            ...                 ...                 ...
460                    10/03/2025                 Yes                 NaN
461                    05/03/2025                 Yes                 NaN
462                    05/03/2025                 Yes                 NaN
463                    05/03/2025                 Yes                 NaN
464                    05/03/2025                 Yes                 NaN

    Applicable % of Tax Rate              Source  \
         Unnamed: 17_level_1 Unnamed: 18_level_1
0                       100%                 NaN
1                       100%                 NaN
2                       100%                 NaN
3                       100%           E-Invoice
4                       100%           E-Invoice
..                       ...                 ...
460                     100%           E-Invoice
461                     100%           E-Invoice
462                     100%           E-Invoice
463                     100%           E-Invoice
464                     100%           E-Invoice

                                                   IRN            IRN Date
                                   Unnamed: 19_level_1 Unnamed: 20_level_1
0                                                  NaN                 NaN
1                                                  NaN                 NaN
2                                                  NaN                 NaN
3    35b64dae4bd14d18f58b09cf1298d5f26d65e79eb77a57...          24/02/2025
4    593070c2921bdf2e9dfe6a003e4946c51513b00d4cedc8...          08/02/2025
..                                                 ...                 ...
460  7d57699b73d108e0f5d8b216d9b9210d8c433cc5353edf...          24/02/2025
461  89c6179d8b06bc1d881e1118c2c2c0c531f59a9921ef2b...          03/02/2025
462  3ee4bca5cc3e17fd5237e04e91655bc247ad54e470b169...          03/02/2025
463  674d3a9036b3f0a5ab3444870a8237c8f1917e64ee305c...          10/02/2025
464  459893d09179a07e7577849a77833d12a2fae4e5414043...          10/02/2025

[465 rows x 21 columns]

In [5]:
df1.columns

Index(['Accounting Date', 'Month', 'Nature', 'Type', 'Supplier', 'GSTIN/UIN',
       'Supplier.1', 'Voucher Type', 'Voucher Number', 'Gross Total', 'Exempt',
       'Taxable @ 5%', 'Taxable @ 12%', 'Taxable @ 18%', 'Taxable @ 28%',
       'Others', 'Taxable Value', 'CGST', 'SGST', 'IGST', 'Cess',
       'Description as per tally', 'Actual description', '%'],
      dtype='str')

In [6]:
df2.columns

MultiIndex([(            'GSTIN of supplier',  'Unnamed: 0_level_1'),
            (             'Trade/Legal name',  'Unnamed: 1_level_1'),
            (              'Invoice Details',      'Invoice number'),
            (              'Invoice Details',        'Invoice type'),
            (              'Invoice Details',        'Invoice Date'),
            (              'Invoice Details',    'Invoice Value(₹)'),
            (              'Place of supply',  'Unnamed: 6_level_1'),
            ('Supply Attract Reverse Charge',  'Unnamed: 7_level_1'),
            (            'Taxable Value (₹)',  'Unnamed: 8_level_1'),
            (                   'Tax Amount',   'Integrated Tax(₹)'),
            (                   'Tax Amount',      'Central Tax(₹)'),
            (                   'Tax Amount',     'State/UT Tax(₹)'),
            (                   'Tax Amount',             'Cess(₹)'),
            (     'GSTR-1/IFF/GSTR-5 Period', 'Unnamed: 13_level_1'),
            ('GSTR-1/IFF/GSTR-5 Filing Date', 'Unnamed: 14_level_1'),
            (             'ITC Availability', 'Unnamed: 15_level_1'),
            (                       'Reason', 'Unnamed: 16_level_1'),
            (     'Applicable % of Tax Rate', 'Unnamed: 17_level_1'),
            (                       'Source', 'Unnamed: 18_level_1'),
            (                          'IRN', 'Unnamed: 19_level_1'),
            (                     'IRN Date', 'Unnamed: 20_level_1')],
           )

In [7]:
df2['GSTIN of supplier']

    Unnamed: 0_level_1
0      33AABCV3609C1ZU
1      33AABCV3609C1ZU
2      29ADKPP9487H1ZL
3      29AAZPN5768K1ZF
4      29AAOFH3996A1Z0
..                 ...
460    29ANCPP7008E1Z1
461    29ADBFS3634C1Z9
462    29ADBFS3634C1Z9
463    29ADBFS3634C1Z9
464    29ADBFS3634C1Z9

[465 rows x 1 columns]

In [8]:
# -------- CLEAN df1 --------

df1 = df1[
    ~(
        df1["Supplier"].isna() &
        df1["Gross Total"].isna()
    )
]


# -------- CLEAN df2 --------

df2 = df2[
    ~(
        df2['Trade/Legal name',  'Unnamed: 1_level_1'].isna() &
        df2["Invoice Details","Invoice Value(₹)"].isna()
    )
]

df1

,Accounting Date,Month,Nature,Type,Supplier,GSTIN/UIN,Supplier.1,Voucher Type,Voucher Number,Gross Total,...,Taxable @ 28%,Others,Taxable Value,CGST,SGST,IGST,Cess,Description as per tally,Actual description,%
0,2025-02-01 00:00:00,2025-02-01,Eligible,Intra-state,NK Enterprises,NaN,NK Enterprises,NaN,NaN,14999.9948,...,0.0,0.0,12711.86,1144.0674,1144.0674,0.0,0.0,Printing & Stationery A/c 18%,Being TK 1178 OG (Toner Cartridge) -Black Cart...,0.18
1,2025-02-04 00:00:00,2025-02-04,Eligible,Intra-state,Sona Roopa,29AACHS2083M1ZO,Sona Roopa,Purchase,8012,16799.9904,...,0.0,0.0,14237.28,1281.3552,1281.3552,0.0,0.0,Printing & Stationery A/c 18%,"Being , Site Stationery Purchased",0.18
2,2025-02-01 00:00:00,2025-02-01,Eligible,Intra-state,Akshaya Groups,29GYXPS5110J1ZJ,Akshaya Groups,Purchase,AK24-25/00872,11446.0000,...,0.0,0.0,9700,873.0000,873.0000,0.0,0.0,Material Purchase @ 18%,"Being Gift -Set, 3 in 1 giftset, Branding charges",0.18
3,2025-02-01 00:00:00,2025-02-01,Eligible,Intra-state,SapanaPlywood and Hardware,29HGDPS9329Q1Z4,SapanaPlywood and Hardware,Purchase,351,47811.2400,...,0.0,0.0,40518,3646.6200,3646.6200,0.0,0.0,Material Purchase @ 18%,"Being Marine plywood 19mm(4x7) , Lam -9015 SO...",0.18
4,2025-02-01 00:00:00,2025-02-01,Eligible,Intra-state,Shri Ganesh Traders,29AEUPD9813N1ZM,Shri Ganesh Traders,Purchase,SGT/23-24/8837,899.7500,...,0.0,0.0,762.5,68.6250,68.6250,0.0,0.0,Material Purchase @ 18%,"Being Cutting Wheel 4"" ,site Material purchased",0.18
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
585,2025-02-25 00:00:00,2025-02-25,Eligible,Intra-state,KBL OD 0777000100021201,29AABCT5589K1ZL,KBL OD 0777000100021201,Payment,29257,59.0000,...,0.0,0.0,50,4.5000,4.5000,0.0,0.0,Bank Charges,Chrgs for RTGS UTR No.:KARBH25056383853_x000D_\n,0.18
586,2025-02-25 00:00:00,2025-02-25,Eligible,Intra-state,KBL OD 0777000100021201,29AABCT5589K1ZL,KBL OD 0777000100021201,Payment,29259,59.0000,...,0.0,0.0,50,4.5000,4.5000,0.0,0.0,Bank Charges,Chrgs for RTGS UTR No.:KARBH25056337828_x000D_\n,0.18
587,2025-02-27 00:00:00,2025-02-27,Eligible,Intra-state,KBL OD 0777000100021201,29AABCT5589K1ZL,KBL OD 0777000100021201,Payment,29272,59.0000,...,0.0,0.0,50,4.5000,4.5000,0.0,0.0,Bank Charges,Chrgs for RTGS UTR No.:KARBH25058713029_x000D_\n,0.18
588,2025-02-28 00:00:00,2025-02-28,Eligible,Intra-state,KBL OD 0777000100021201,29AABCT5589K1ZL,KBL OD 0777000100021201,Payment,29283,59.0000,...,0.0,0.0,50,4.5000,4.5000,0.0,0.0,Bank Charges,Chrgs for RTGS UTR No.:KARBH25059953391_x000D_\n,0.18
589,2025-02-28 00:00:00,2025-02-28,Eligible,Intra-state,KBL OD 0777000100021201,29AABCT5589K1ZL,KBL OD 0777000100021201,Payment,29287,17.3814,...,0.0,0.0,14.73,1.3257,1.3257,0.0,0.0,Bank Charges,Chrgs for NEFT UTR No.:KARBN25059984420_x000D_\n,0.18

In [9]:
#fix dates

df1["Accounting Date"] = pd.to_datetime(
    df1["Accounting Date"],
    errors="coerce"
)

df2[("Invoice Details", "Invoice Date")] = pd.to_datetime(
    df2[("Invoice Details", "Invoice Date")],
    errors="coerce"
)

In [10]:
# Fix numerical columns and recompute books money from rate-wise taxable columns

rate_cols = {
    "Taxable @ 0%": 0.00,
    "Taxable @ 5%": 0.05,
    "Taxable @ 12%": 0.12,
    "Taxable @ 18%": 0.18,
    "Taxable @ 28%": 0.28,
}

# Convert all money inputs we may use. Missing columns are ignored so the cell stays reusable.
df1_numeric_cols = [
    "Gross Total",
    "Taxable Value",
    "CGST",
    "SGST",
    "IGST",
    "Cess",
    "Exempt",
    "Others",
    *rate_cols.keys(),
]

for col in df1_numeric_cols:
    if col in df1.columns:
        df1[col] = pd.to_numeric(df1[col], errors="coerce").fillna(0)


df2_numeric_cols = [
    ("Invoice Details", "Invoice Value(₹)"),
    ("Taxable Value (₹)", "Unnamed: 8_level_1"),
    ("Tax Amount", "Central Tax(₹)"),
    ("Tax Amount", "State/UT Tax(₹)"),
    ("Tax Amount", "Integrated Tax(₹)")
]

for col in df2_numeric_cols:
    df2[col] = pd.to_numeric(df2[col], errors="coerce").fillna(0)

available_rate_cols = [col for col in rate_cols if col in df1.columns]
is_intra_state = df1["Type"].astype("string").str.upper().str.contains("INTRA", na=False)

recomputed_taxable = sum(df1[col] for col in available_rate_cols)
recomputed_cgst = sum(df1[col] * (rate / 2) for col, rate in rate_cols.items() if col in df1.columns)
recomputed_sgst = recomputed_cgst.copy()
recomputed_igst = sum(df1[col] * rate for col, rate in rate_cols.items() if col in df1.columns)

# Preserve the loaded formula values for audit, then replace them with recomputed values.
df1["taxable_value_loaded"] = df1["Taxable Value"]
df1["cgst_loaded"] = df1["CGST"]
df1["sgst_loaded"] = df1["SGST"]
df1["igst_loaded"] = df1["IGST"]

df1["Taxable Value"] = recomputed_taxable.round(2)
df1["CGST"] = recomputed_cgst.where(is_intra_state, 0).round(2)
df1["SGST"] = recomputed_sgst.where(is_intra_state, 0).round(2)
df1["IGST"] = recomputed_igst.where(~is_intra_state, 0).round(2)

cess = df1["Cess"] if "Cess" in df1.columns else 0
exempt = df1["Exempt"] if "Exempt" in df1.columns else 0
others = df1["Others"] if "Others" in df1.columns else 0

df1["gross_total_recomputed"] = (
    df1["Taxable Value"] + df1["CGST"] + df1["SGST"] + df1["IGST"] + cess + exempt + others
).round(2)

df1["gross_total_diff"] = (df1["Gross Total"] - df1["gross_total_recomputed"]).round(2)
dirty_input = df1[df1["gross_total_diff"].abs() > 2].copy()

print(f"Dirty input rows needing review: {len(dirty_input)}")

Dirty input rows needing review: 0

In [11]:
# -------- TRIM SPACES --------

df1["Supplier"] = (
    df1["Supplier"]
    .astype("string")
    .str.strip()
    .str.upper()
)


df2[("Trade/Legal name", "Unnamed: 1_level_1")] = (
    df2[("Trade/Legal name", "Unnamed: 1_level_1")]
    .astype("string")
    .str.strip()
    .str.upper()
)

In [12]:
#cleaning trailing and leading spaces in invoice number and gstin columns

df1["Voucher Number"] = (
    df1["Voucher Number"]
    .astype("string")
    .str.strip()
    .str.upper()
)
df1["GSTIN/UIN"] = (
    df1["GSTIN/UIN"]
    .astype("string")
    .str.strip()
    .str.upper()
)

df2[("Invoice Details", "Invoice number")] = (
    df2[("Invoice Details", "Invoice number")]
    .astype("string")
    .str.strip()
    .str.upper()
)

df2[("GSTIN of supplier", "Unnamed: 0_level_1")] = (
    df2[("GSTIN of supplier", "Unnamed: 0_level_1")]
    .astype("string")
    .str.strip()
    .str.upper()
)

In [13]:
# -------- ROUND NUMERIC VALUES --------

money_cols = [
    "Gross Total",
    "Taxable Value",
    "CGST",
    "SGST",
    "IGST",
    "gross_total_recomputed",
    "gross_total_diff",
]

for col in money_cols:
    if col in df1.columns:
        df1[col] = df1[col].round(2)

df2[("Invoice Details", "Invoice Value(₹)")] = (
    df2[("Invoice Details", "Invoice Value(₹)")]
    .round(2)
)

In [14]:
# Duplicate row count in df1
#keep the duplicated rows in mind if any
df1_duplicates = df1.duplicated().sum()

# Duplicate row count in df2
df2_duplicates = df2.duplicated().sum()

print("df1 duplicate rows:", df1_duplicates)
print("df2 duplicate rows:", df2_duplicates)

df1 duplicate rows: 0
df2 duplicate rows: 0

In [15]:
# Create dataframe with MultiIndex columns

combined_df = pd.DataFrame({

    # -------- df1 --------
    ("df1", "date"): df1["Accounting Date"],
    ("df1", "gstin"): df1["GSTIN/UIN"],
    ("df1", "supplier"): df1["Supplier"],
    ("df1", "taxable_value"): df1["Taxable Value"],
    ("df1", "cgst"): df1["CGST"],
    ("df1", "sgst"): df1["SGST"],
    ("df1", "igst"): df1["IGST"],
    ("df1", "voucher_number"): df1["Voucher Number"],
    ("df1", "invoice_value"): df1["Gross Total"],

    # -------- df2 --------
    ("df2", "date"): df2[("Invoice Details", "Invoice Date")],
    ("df2", "gstin"): df2[("GSTIN of supplier", "Unnamed: 0_level_1")],
    ("df2", "supplier"): df2[("Trade/Legal name", "Unnamed: 1_level_1")],
    ("df2", "taxable_value"): df2[("Taxable Value (₹)", "Unnamed: 8_level_1")],
    ("df2", "cgst"): df2[("Tax Amount", "Central Tax(₹)")],
    ("df2", "sgst"): df2[("Tax Amount", "State/UT Tax(₹)")],
    ("df2", "igst"): df2[("Tax Amount", "Integrated Tax(₹)")],
    ("df2", "invoice_number"): df2[("Invoice Details", "Invoice number")],
    ("df2", "invoice_value"): df2[("Invoice Details", "Invoice Value(₹)")]

})

# Convert columns to MultiIndex
combined_df.columns = pd.MultiIndex.from_tuples(combined_df.columns)

print(combined_df.head())

         df1                                                             \
        date            gstin                    supplier taxable_value
0 2025-02-01             <NA>              NK ENTERPRISES      12711.86
1 2025-02-04  29AACHS2083M1ZO                  SONA ROOPA      14237.28
2 2025-02-01  29GYXPS5110J1ZJ              AKSHAYA GROUPS       9700.00
3 2025-02-01  29HGDPS9329Q1Z4  SAPANAPLYWOOD AND HARDWARE      40518.00
4 2025-02-01  29AEUPD9813N1ZM         SHRI GANESH TRADERS        762.50

                                                              df2  \
      cgst     sgst igst  voucher_number invoice_value       date
0  1144.07  1144.07  0.0            <NA>      14999.99 2025-06-02
1  1281.36  1281.36  0.0            8012      16799.99        NaT
2   873.00   873.00  0.0   AK24-25/00872      11446.00        NaT
3  3646.62  3646.62  0.0             351      47811.24        NaT
4    68.62    68.62  0.0  SGT/23-24/8837        899.75 2025-08-02

                                                                               \
             gstin                             supplier taxable_value    cgst
0  33AABCV3609C1ZU                VRL LOGISTICS LIMITED       2890.00    0.00
1  33AABCV3609C1ZU                VRL LOGISTICS LIMITED        490.00    0.00
2  29ADKPP9487H1ZL                     MAHESH HARDWARES       1101.70   99.15
3  29AAZPN5768K1ZF  SHRI SHANTESHWAR ENGINERING COMPNAY        635.59   57.20
4  29AAOFH3996A1Z0          HITECH ENGINEERING SERVICES       7000.00  630.00


     sgst   igst  invoice_number invoice_value
0    0.00  144.5      2693198910        2890.0
1    0.00   24.5      3247580610         490.0
2   99.15    0.0            3264        1300.0
3   57.20    0.0  SSE/2079/24-25         750.0
4  630.00    0.0        B2BS-164        8260.0

In [16]:
combined_df

           df1                                                             \
          date            gstin                    supplier taxable_value
0   2025-02-01             <NA>              NK ENTERPRISES      12711.86
1   2025-02-04  29AACHS2083M1ZO                  SONA ROOPA      14237.28
2   2025-02-01  29GYXPS5110J1ZJ              AKSHAYA GROUPS       9700.00
3   2025-02-01  29HGDPS9329Q1Z4  SAPANAPLYWOOD AND HARDWARE      40518.00
4   2025-02-01  29AEUPD9813N1ZM         SHRI GANESH TRADERS        762.50
..         ...              ...                         ...           ...
585 2025-02-25  29AABCT5589K1ZL     KBL OD 0777000100021201         50.00
586 2025-02-25  29AABCT5589K1ZL     KBL OD 0777000100021201         50.00
587 2025-02-27  29AABCT5589K1ZL     KBL OD 0777000100021201         50.00
588 2025-02-28  29AABCT5589K1ZL     KBL OD 0777000100021201         50.00
589 2025-02-28  29AABCT5589K1ZL     KBL OD 0777000100021201         14.73

                                                                df2  \
        cgst     sgst igst  voucher_number invoice_value       date
0    1144.07  1144.07  0.0            <NA>      14999.99 2025-06-02
1    1281.36  1281.36  0.0            8012      16799.99        NaT
2     873.00   873.00  0.0   AK24-25/00872      11446.00        NaT
3    3646.62  3646.62  0.0             351      47811.24        NaT
4      68.62    68.62  0.0  SGT/23-24/8837        899.75 2025-08-02
..       ...      ...  ...             ...           ...        ...
585     4.50     4.50  0.0           29257         59.00        NaT
586     4.50     4.50  0.0           29259         59.00        NaT
587     4.50     4.50  0.0           29272         59.00        NaT
588     4.50     4.50  0.0           29283         59.00        NaT
589     1.33     1.33  0.0           29287         17.38        NaT

                                                                         \
               gstin                             supplier taxable_value
0    33AABCV3609C1ZU                VRL LOGISTICS LIMITED       2890.00
1    33AABCV3609C1ZU                VRL LOGISTICS LIMITED        490.00
2    29ADKPP9487H1ZL                     MAHESH HARDWARES       1101.70
3    29AAZPN5768K1ZF  SHRI SHANTESHWAR ENGINERING COMPNAY        635.59
4    29AAOFH3996A1Z0          HITECH ENGINEERING SERVICES       7000.00
..               ...                                  ...           ...
585             <NA>                                 <NA>           NaN
586             <NA>                                 <NA>           NaN
587             <NA>                                 <NA>           NaN
588             <NA>                                 <NA>           NaN
589             <NA>                                 <NA>           NaN


       cgst    sgst   igst  invoice_number invoice_value
0      0.00    0.00  144.5      2693198910        2890.0
1      0.00    0.00   24.5      3247580610         490.0
2     99.15   99.15    0.0            3264        1300.0
3     57.20   57.20    0.0  SSE/2079/24-25         750.0
4    630.00  630.00    0.0        B2BS-164        8260.0
..      ...     ...    ...             ...           ...
585     NaN     NaN    NaN            <NA>           NaN
586     NaN     NaN    NaN            <NA>           NaN
587     NaN     NaN    NaN            <NA>           NaN
588     NaN     NaN    NaN            <NA>           NaN
589     NaN     NaN    NaN            <NA>           NaN

[590 rows x 18 columns]

In [17]:
# Count null values for each column
null_counts = combined_df.isnull().sum()

print(null_counts)

df1  date                0
     gstin              40
     supplier            0
     taxable_value       0
     cgst                0
     sgst                0
     igst                0
     voucher_number      1
     invoice_value       0
df2  date              428
     gstin             125
     supplier          125
     taxable_value     125
     cgst              125
     sgst              125
     igst              125
     invoice_number    125
     invoice_value     125
dtype: int64

In [18]:
# Rows where df1 date is null
null_df1_date_rows = combined_df[
    combined_df[("df1", "date")].isnull()
]
(null_df1_date_rows)

#verdict:
# no values with null dates when there is an entry

Empty DataFrame
Columns: [(df1, date), (df1, gstin), (df1, supplier), (df1, taxable_value), (df1, cgst), (df1, sgst), (df1, igst), (df1, voucher_number), (df1, invoice_value), (df2, date), (df2, gstin), (df2, supplier), (df2, taxable_value), (df2, cgst), (df2, sgst), (df2, igst), (df2, invoice_number), (df2, invoice_value)]
Index: []

In [19]:
# Rows where df1 supplier is null
null_df1_supplier_rows = combined_df[
    combined_df[("df1", "supplier")].isnull()
]
(null_df1_supplier_rows)

#verdict
# no values with supplier null when there is an entry

Empty DataFrame
Columns: [(df1, date), (df1, gstin), (df1, supplier), (df1, taxable_value), (df1, cgst), (df1, sgst), (df1, igst), (df1, voucher_number), (df1, invoice_value), (df2, date), (df2, gstin), (df2, supplier), (df2, taxable_value), (df2, cgst), (df2, sgst), (df2, igst), (df2, invoice_number), (df2, invoice_value)]
Index: []

In [20]:
# Rows where df1 invoice value is null
null_df1_invoice_value_rows = combined_df[
    combined_df[("df1", "invoice_value")].isnull()
]
(null_df1_invoice_value_rows)

#verdict
# no values with invoice value null when there is an entry

Empty DataFrame
Columns: [(df1, date), (df1, gstin), (df1, supplier), (df1, taxable_value), (df1, cgst), (df1, sgst), (df1, igst), (df1, voucher_number), (df1, invoice_value), (df2, date), (df2, gstin), (df2, supplier), (df2, taxable_value), (df2, cgst), (df2, sgst), (df2, igst), (df2, invoice_number), (df2, invoice_value)]
Index: []

In [21]:
print(combined_df.columns)

MultiIndex([('df1',           'date'),
            ('df1',          'gstin'),
            ('df1',       'supplier'),
            ('df1',  'taxable_value'),
            ('df1',           'cgst'),
            ('df1',           'sgst'),
            ('df1',           'igst'),
            ('df1', 'voucher_number'),
            ('df1',  'invoice_value'),
            ('df2',           'date'),
            ('df2',          'gstin'),
            ('df2',       'supplier'),
            ('df2',  'taxable_value'),
            ('df2',           'cgst'),
            ('df2',           'sgst'),
            ('df2',           'igst'),
            ('df2', 'invoice_number'),
            ('df2',  'invoice_value')],
           )

# **Data reconcillation**

In [22]:
df1

,Accounting Date,Month,Nature,Type,Supplier,GSTIN/UIN,Supplier.1,Voucher Type,Voucher Number,Gross Total,...,Cess,Description as per tally,Actual description,%,taxable_value_loaded,cgst_loaded,sgst_loaded,igst_loaded,gross_total_recomputed,gross_total_diff
0,2025-02-01,2025-02-01,Eligible,Intra-state,NK ENTERPRISES,<NA>,NK Enterprises,NaN,<NA>,14999.99,...,0.0,Printing & Stationery A/c 18%,Being TK 1178 OG (Toner Cartridge) -Black Cart...,0.18,12711.86,1144.0674,1144.0674,0.0,15000.00,-0.01
1,2025-02-04,2025-02-04,Eligible,Intra-state,SONA ROOPA,29AACHS2083M1ZO,Sona Roopa,Purchase,8012,16799.99,...,0.0,Printing & Stationery A/c 18%,"Being , Site Stationery Purchased",0.18,14237.28,1281.3552,1281.3552,0.0,16800.00,-0.01
2,2025-02-01,2025-02-01,Eligible,Intra-state,AKSHAYA GROUPS,29GYXPS5110J1ZJ,Akshaya Groups,Purchase,AK24-25/00872,11446.00,...,0.0,Material Purchase @ 18%,"Being Gift -Set, 3 in 1 giftset, Branding charges",0.18,9700.00,873.0000,873.0000,0.0,11446.00,0.00
3,2025-02-01,2025-02-01,Eligible,Intra-state,SAPANAPLYWOOD AND HARDWARE,29HGDPS9329Q1Z4,SapanaPlywood and Hardware,Purchase,351,47811.24,...,0.0,Material Purchase @ 18%,"Being Marine plywood 19mm(4x7) , Lam -9015 SO...",0.18,40518.00,3646.6200,3646.6200,0.0,47811.24,0.00
4,2025-02-01,2025-02-01,Eligible,Intra-state,SHRI GANESH TRADERS,29AEUPD9813N1ZM,Shri Ganesh Traders,Purchase,SGT/23-24/8837,899.75,...,0.0,Material Purchase @ 18%,"Being Cutting Wheel 4"" ,site Material purchased",0.18,762.50,68.6250,68.6250,0.0,899.74,0.01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
585,2025-02-25,2025-02-25,Eligible,Intra-state,KBL OD 0777000100021201,29AABCT5589K1ZL,KBL OD 0777000100021201,Payment,29257,59.00,...,0.0,Bank Charges,Chrgs for RTGS UTR No.:KARBH25056383853_x000D_\n,0.18,50.00,4.5000,4.5000,0.0,59.00,0.00
586,2025-02-25,2025-02-25,Eligible,Intra-state,KBL OD 0777000100021201,29AABCT5589K1ZL,KBL OD 0777000100021201,Payment,29259,59.00,...,0.0,Bank Charges,Chrgs for RTGS UTR No.:KARBH25056337828_x000D_\n,0.18,50.00,4.5000,4.5000,0.0,59.00,0.00
587,2025-02-27,2025-02-27,Eligible,Intra-state,KBL OD 0777000100021201,29AABCT5589K1ZL,KBL OD 0777000100021201,Payment,29272,59.00,...,0.0,Bank Charges,Chrgs for RTGS UTR No.:KARBH25058713029_x000D_\n,0.18,50.00,4.5000,4.5000,0.0,59.00,0.00
588,2025-02-28,2025-02-28,Eligible,Intra-state,KBL OD 0777000100021201,29AABCT5589K1ZL,KBL OD 0777000100021201,Payment,29283,59.00,...,0.0,Bank Charges,Chrgs for RTGS UTR No.:KARBH25059953391_x000D_\n,0.18,50.00,4.5000,4.5000,0.0,59.00,0.00
589,2025-02-28,2025-02-28,Eligible,Intra-state,KBL OD 0777000100021201,29AABCT5589K1ZL,KBL OD 0777000100021201,Payment,29287,17.38,...,0.0,Bank Charges,Chrgs for NEFT UTR No.:KARBN25059984420_x000D_\n,0.18,14.73,1.3257,1.3257,0.0,17.39,-0.01

In [23]:
df1.columns

Index(['Accounting Date', 'Month', 'Nature', 'Type', 'Supplier', 'GSTIN/UIN',
       'Supplier.1', 'Voucher Type', 'Voucher Number', 'Gross Total', 'Exempt',
       'Taxable @ 5%', 'Taxable @ 12%', 'Taxable @ 18%', 'Taxable @ 28%',
       'Others', 'Taxable Value', 'CGST', 'SGST', 'IGST', 'Cess',
       'Description as per tally', 'Actual description', '%',
       'taxable_value_loaded', 'cgst_loaded', 'sgst_loaded', 'igst_loaded',
       'gross_total_recomputed', 'gross_total_diff'],
      dtype='str')

In [24]:
gstr2b = df2

In [25]:
df2.columns

MultiIndex([(            'GSTIN of supplier',  'Unnamed: 0_level_1'),
            (             'Trade/Legal name',  'Unnamed: 1_level_1'),
            (              'Invoice Details',      'Invoice number'),
            (              'Invoice Details',        'Invoice type'),
            (              'Invoice Details',        'Invoice Date'),
            (              'Invoice Details',    'Invoice Value(₹)'),
            (              'Place of supply',  'Unnamed: 6_level_1'),
            ('Supply Attract Reverse Charge',  'Unnamed: 7_level_1'),
            (            'Taxable Value (₹)',  'Unnamed: 8_level_1'),
            (                   'Tax Amount',   'Integrated Tax(₹)'),
            (                   'Tax Amount',      'Central Tax(₹)'),
            (                   'Tax Amount',     'State/UT Tax(₹)'),
            (                   'Tax Amount',             'Cess(₹)'),
            (     'GSTR-1/IFF/GSTR-5 Period', 'Unnamed: 13_level_1'),
            ('GSTR-1/IFF/GSTR-5 Filing Date', 'Unnamed: 14_level_1'),
            (             'ITC Availability', 'Unnamed: 15_level_1'),
            (                       'Reason', 'Unnamed: 16_level_1'),
            (     'Applicable % of Tax Rate', 'Unnamed: 17_level_1'),
            (                       'Source', 'Unnamed: 18_level_1'),
            (                          'IRN', 'Unnamed: 19_level_1'),
            (                     'IRN Date', 'Unnamed: 20_level_1')],
           )

In [26]:
# Group books to invoice level before matching.
# Design rule:
# - GSTIN + invoice present -> group by GSTIN + invoice
# - GSTIN missing + invoice present -> fallback group by supplier + invoice
# - invoice missing -> keep standalone, because invoice-grain grouping is unsafe

matchable_books = df1.drop(index=dirty_input.index).copy()

gstin_present = matchable_books["GSTIN/UIN"].notna()
invoice_present = matchable_books["Voucher Number"].notna()

gstin_invoice_mask = gstin_present & invoice_present
supplier_invoice_mask = (~gstin_present) & invoice_present
standalone_mask = ~invoice_present

# Start every row as standalone; then only safe rows get grouped.
standalone_key = "standalone_" + matchable_books.index.astype("string")

matchable_books["group_key_type"] = "standalone_missing_invoice"
matchable_books["group_key_1"] = standalone_key
matchable_books["group_key_2"] = standalone_key

# Primary grouping: GSTIN + invoice
matchable_books.loc[gstin_invoice_mask, "group_key_type"] = "gstin_invoice"
matchable_books.loc[gstin_invoice_mask, "group_key_1"] = matchable_books.loc[gstin_invoice_mask, "GSTIN/UIN"]
matchable_books.loc[gstin_invoice_mask, "group_key_2"] = matchable_books.loc[gstin_invoice_mask, "Voucher Number"]

# Fallback grouping: supplier + invoice, only when GSTIN is missing
matchable_books.loc[supplier_invoice_mask, "group_key_type"] = "supplier_invoice"
matchable_books.loc[supplier_invoice_mask, "group_key_1"] = matchable_books.loc[supplier_invoice_mask, "Supplier"]
matchable_books.loc[supplier_invoice_mask, "group_key_2"] = matchable_books.loc[supplier_invoice_mask, "Voucher Number"]

books_grouped = (
    matchable_books.groupby(
        ["group_key_type", "group_key_1", "group_key_2"],
        dropna=False,
    )
    .agg(
        Supplier=("Supplier", "first"),
        **{"Voucher Number": ("Voucher Number", "first")},
        gstin=("GSTIN/UIN", "first"),
        date=("Accounting Date", "first"),
        taxable_value=("Taxable Value", "sum"),
        cgst=("CGST", "sum"),
        sgst=("SGST", "sum"),
        igst=("IGST", "sum"),
        gross_total=("Gross Total", "sum"),
        source_rows=("Voucher Number", lambda x: list(x.index)),
    )
    .reset_index()
    .reset_index()
    .rename(columns={"index": "books_group_idx"})
)

books_grouped["total_tax"] = (
    books_grouped["cgst"] + books_grouped["sgst"] + books_grouped["igst"]
).round(2)

books_grouped.head()

,books_group_idx,group_key_type,group_key_1,group_key_2,Supplier,Voucher Number,gstin,date,taxable_value,cgst,sgst,igst,gross_total,source_rows,total_tax
0,0,gstin_invoice,07ALEPK3083E1ZB,2024-25/2174,KHURANA MOTORS,2024-25/2174,07ALEPK3083E1ZB,2025-02-11,17000.0,0.0,0.0,3060.0,20060.0,[550],3060.0
1,1,gstin_invoice,07ALEPK3083E1ZB,2024-25/2178,KHURANA MOTORS,2024-25/2178,07ALEPK3083E1ZB,2025-02-11,26975.0,0.0,0.0,4855.5,31830.5,[551],4855.5
2,2,gstin_invoice,07ALEPK3083E1ZB,2024-25/2334,KHURANA MOTORS,2024-25/2334,07ALEPK3083E1ZB,2025-02-28,14950.0,0.0,0.0,2691.0,17641.0,[552],2691.0
3,3,gstin_invoice,10FGTPK5221F1ZL,29,UPENDRA KUMAR KUSHWAHA,29,10FGTPK5221F1ZL,2025-02-01,160000.0,0.0,0.0,28800.0,188800.0,[537],28800.0
4,4,gstin_invoice,27AACFU8905A1ZC_X000D_,UCM/24-25/879,UCHAGAONKAR CONSTRUCTION MACHINERY_X000D_,UCM/24-25/879,27AACFU8905A1ZC_X000D_,2025-02-20,1999370.0,0.0,0.0,359886.6,2359256.6,[542],359886.6

In [27]:
TOL = 2  # ₹2 tolerance

tax_columns = ["cgst", "sgst", "igst"]

def money_matches(b, g):
    taxable_match = abs(b["taxable_value"] - g["taxable_value"]) <= TOL
    component_tax_match = all(
        abs(b[col] - g[col]) <= TOL
        for col in tax_columns
    )

    # Allows CGST+SGST in one file vs IGST in the other when total tax agrees.
    total_tax_match = abs(
        (b["cgst"] + b["sgst"] + b["igst"]) -
        (g["cgst"] + g["sgst"] + g["igst"])
    ) <= TOL

    return taxable_match and (component_tax_match or total_tax_match)

In [28]:
# Keep df2 with its original MultiIndex columns, and create a flat working copy for matching.
df2_flat = df2.copy()
df2_flat.columns = [
    a if "Unnamed" in b else f"{a}_{b}"
    for a, b in df2_flat.columns
]

gstr2b = df2_flat.rename(columns={
    "GSTIN of supplier": "gstin",
    "Trade/Legal name": "supplier",
    "Invoice Details_Invoice number": "invoice_number",
    "Invoice Details_Invoice Date": "date",
    "Invoice Details_Invoice Value(₹)": "invoice_value",
    "Taxable Value (₹)": "taxable_value",
    "Tax Amount_Central Tax(₹)": "cgst",
    "Tax Amount_State/UT Tax(₹)": "sgst",
    "Tax Amount_Integrated Tax(₹)": "igst",
})

gstr2b = gstr2b.reset_index().rename(columns={"index": "gstr2b_idx"})
gstr2b.head()

,gstr2b_idx,gstin,supplier,invoice_number,Invoice Details_Invoice type,date,invoice_value,Place of supply,Supply Attract Reverse Charge,taxable_value,...,sgst,Tax Amount_Cess(₹),GSTR-1/IFF/GSTR-5 Period,GSTR-1/IFF/GSTR-5 Filing Date,ITC Availability,Reason,Applicable % of Tax Rate,Source,IRN,IRN Date
0,0,33AABCV3609C1ZU,VRL LOGISTICS LIMITED,2693198910,Regular,2025-06-02,2890.0,Karnataka,Yes,2890.00,...,0.00,0,Feb'25,11/03/2025,Yes,NaN,100%,NaN,NaN,NaN
1,1,33AABCV3609C1ZU,VRL LOGISTICS LIMITED,3247580610,Regular,NaT,490.0,Karnataka,Yes,490.00,...,0.00,0,Feb'25,11/03/2025,Yes,NaN,100%,NaN,NaN,NaN
2,2,29ADKPP9487H1ZL,MAHESH HARDWARES,3264,Regular,NaT,1300.0,Karnataka,No,1101.70,...,99.15,0,Feb'25,09/03/2025,Yes,NaN,100%,NaN,NaN,NaN
3,3,29AAZPN5768K1ZF,SHRI SHANTESHWAR ENGINERING COMPNAY,SSE/2079/24-25,Regular,NaT,750.0,Karnataka,No,635.59,...,57.20,0,Feb'25,11/03/2025,Yes,NaN,100%,E-Invoice,35b64dae4bd14d18f58b09cf1298d5f26d65e79eb77a57...,24/02/2025
4,4,29AAOFH3996A1Z0,HITECH ENGINEERING SERVICES,B2BS-164,Regular,2025-08-02,8260.0,Karnataka,No,7000.00,...,630.00,0,Feb'25,11/03/2025,Yes,NaN,100%,E-Invoice,593070c2921bdf2e9dfe6a003e4946c51513b00d4cedc8...,08/02/2025

In [29]:
TOL = 2

books_r = books_grouped.copy()
gstr2b_r = gstr2b.copy()

# Branch 1: GSTIN + invoice must both match (design.md sheet 1A, first condition).
# This prevents a books row from matching a 2B row that merely shares its GSTIN.
merge_gstin_invoice = books_r.merge(
    gstr2b_r,
    left_on=["gstin", "Voucher Number"],
    right_on=["gstin", "invoice_number"],
    how="inner",
    suffixes=("_b", "_g")
)

# Branch 2: invoice + supplier must both match (design.md sheet 1A, second condition).
# Covers no-GSTIN rows and mistyped-GSTIN rows where invoice and supplier agree.
# This prevents a books row from matching a 2B row that merely shares its invoice number.
merge_invoice_supplier = books_r.merge(
    gstr2b_r,
    left_on=["Voucher Number", "Supplier"],
    right_on=["invoice_number", "supplier"],
    how="inner",
    suffixes=("_b", "_g")
)

candidates = pd.concat([merge_gstin_invoice, merge_invoice_supplier], ignore_index=True).drop_duplicates(
    subset=["books_group_idx", "gstr2b_idx"]
)

# Apply money tolerance filter. Tax buckets may match component-wise or by total tax.
taxable_match = abs(candidates["taxable_value_b"] - candidates["taxable_value_g"]) <= TOL
component_tax_match = (
    (abs(candidates["cgst_b"] - candidates["cgst_g"]) <= TOL) &
    (abs(candidates["sgst_b"] - candidates["sgst_g"]) <= TOL) &
    (abs(candidates["igst_b"] - candidates["igst_g"]) <= TOL)
)
total_tax_match = abs(
    (candidates["cgst_b"] + candidates["sgst_b"] + candidates["igst_b"]) -
    (candidates["cgst_g"] + candidates["sgst_g"] + candidates["igst_g"])
) <= TOL

sheet1_candidates = candidates[
    taxable_match & (component_tax_match | total_tax_match)
].copy()

# Ranking follows design.md section 7.
# invoice_exact: always True here (both branches require invoice to match), used as sanity check.
# gstin_exact: True only for branch-1 rows (joined on gstin); NaN for branch-2 rows after concat.
# supplier_exact: True for branch-2 rows (joined on supplier); may vary for branch-1 rows.
sheet1_candidates["invoice_exact"] = (
    sheet1_candidates["Voucher Number"] == sheet1_candidates["invoice_number"]
)
sheet1_candidates["gstin_exact"] = sheet1_candidates["gstin"].notna()
sheet1_candidates["supplier_exact"] = (
    sheet1_candidates["Supplier"] == sheet1_candidates["supplier"]
)
sheet1_candidates["total_money_diff"] = (
    (sheet1_candidates["taxable_value_b"] - sheet1_candidates["taxable_value_g"]).abs() +
    (sheet1_candidates["cgst_b"] - sheet1_candidates["cgst_g"]).abs() +
    (sheet1_candidates["sgst_b"] - sheet1_candidates["sgst_g"]).abs() +
    (sheet1_candidates["igst_b"] - sheet1_candidates["igst_g"]).abs()
)
sheet1_candidates["date_diff_days"] = (
    sheet1_candidates["date_b"] - sheet1_candidates["date_g"]
).abs().dt.days.fillna(999999)

complete_cols = ["gstin", "Voucher Number", "Supplier", "invoice_number", "supplier"]
sheet1_candidates["blank_count"] = sheet1_candidates[complete_cols].isna().sum(axis=1)

sheet1_candidates = sheet1_candidates.sort_values(
    by=[
        "invoice_exact",
        "gstin_exact",
        "supplier_exact",
        "total_money_diff",
        "date_diff_days",
        "blank_count",
    ],
    ascending=[False, False, False, True, True, True]
)

accepted_rows = []
needs_review_sheet1 = []
used_books = set()
used_gstr2b = set()

rank_cols = [
    "invoice_exact",
    "gstin_exact",
    "supplier_exact",
    "total_money_diff",
    "date_diff_days",
    "blank_count",
]

for books_id, group in sheet1_candidates.groupby("books_group_idx", sort=False):
    available = group[
        ~group["books_group_idx"].isin(used_books) &
        ~group["gstr2b_idx"].isin(used_gstr2b)
    ]

    if available.empty:
        continue

    best = available.iloc[0]
    tied_best = available[
        (available[rank_cols] == best[rank_cols]).all(axis=1)
    ]

    if len(tied_best) > 1:
        needs_review_sheet1.append(tied_best)
        continue

    accepted_rows.append(best)
    used_books.add(best["books_group_idx"])
    used_gstr2b.add(best["gstr2b_idx"])

sheet1a = pd.DataFrame(accepted_rows)
needs_review_sheet1 = (
    pd.concat(needs_review_sheet1, ignore_index=True)
    if needs_review_sheet1 else
    pd.DataFrame(columns=sheet1_candidates.columns)
)

books_pool = books_grouped[~books_grouped["books_group_idx"].isin(used_books)].copy()
gstr2b_pool = gstr2b[~gstr2b["gstr2b_idx"].isin(used_gstr2b)].copy()

print(f"Sheet 1A candidates: {len(sheet1_candidates)}")
print(f"Sheet 1A one-to-one matches: {len(sheet1a)}")
print(f"Sheet 1A needs review ties: {len(needs_review_sheet1)}")
print(f"Books groups remaining: {len(books_pool)}")
print(f"2B remaining: {len(gstr2b_pool)}")

Sheet 1A candidates: 330
Sheet 1A one-to-one matches: 330
Sheet 1A needs review ties: 0
Books groups remaining: 190
2B remaining: 135

In [30]:
import re

# Reuse if Sheet 2 already ran, otherwise define here
try:
    standardize_invoice
except NameError:
    def standardize_invoice(val):
        if pd.isna(val) or str(val).strip() in ("", "<NA>", "nan"):
            return None
        s = re.sub(r"[\s/\-]+", "", str(val)).upper().lstrip("0")
        return s if s else None

# -------- SHEET 1B / 1C --------
# money + GSTIN  OR  money + supplier,  invoice does NOT match (exact or standardized)
# 1B: amount unique for that identity on both sides  →  auto-match
# 1C: amount not unique (collision)                  →  blue

books_1bc  = books_pool.copy()
gstr2b_1bc = gstr2b_pool.copy()
books_1bc["std_voucher"]  = books_1bc["Voucher Number"].apply(standardize_invoice)
gstr2b_1bc["std_invoice"] = gstr2b_1bc["invoice_number"].apply(standardize_invoice)

# Branch A: GSTIN identity
branch_a = books_1bc.merge(gstr2b_1bc, on="gstin", how="inner", suffixes=("_b", "_g"))
branch_a["match_branch"] = "gstin"

# Branch B: supplier identity
branch_b = books_1bc.merge(
    gstr2b_1bc,
    left_on="Supplier", right_on="supplier",
    how="inner", suffixes=("_b", "_g")
)
branch_b["match_branch"] = "supplier"
branch_b["gstin"] = branch_b["gstin_b"]   # normalize: "gstin" column always exists after concat

cands_1bc = pd.concat([branch_a, branch_b], ignore_index=True).drop_duplicates(
    subset=["books_group_idx", "gstr2b_idx"]
)

# Money filter
tv_ok   = abs(cands_1bc["taxable_value_b"] - cands_1bc["taxable_value_g"]) <= TOL
comp_ok = (
    (abs(cands_1bc["cgst_b"] - cands_1bc["cgst_g"]) <= TOL) &
    (abs(cands_1bc["sgst_b"] - cands_1bc["sgst_g"]) <= TOL) &
    (abs(cands_1bc["igst_b"] - cands_1bc["igst_g"]) <= TOL)
)
tot_ok  = abs(
    (cands_1bc["cgst_b"] + cands_1bc["sgst_b"] + cands_1bc["igst_b"]) -
    (cands_1bc["cgst_g"] + cands_1bc["sgst_g"] + cands_1bc["igst_g"])
) <= TOL
cands_1bc = cands_1bc[tv_ok & (comp_ok | tot_ok)].copy()

# Drop invoice-exact pairs — those belong in 1A / Sheet 2
inv_exact = cands_1bc["Voucher Number"] == cands_1bc["invoice_number"]
std_exact = (
    cands_1bc["std_voucher"].notna() &
    cands_1bc["std_invoice"].notna() &
    (cands_1bc["std_voucher"] == cands_1bc["std_invoice"])
)
cands_1bc = cands_1bc[~(inv_exact | std_exact)].copy()

# -------- Uniqueness: count (identity, taxable_value) occurrences in each pool --------
books_gstin_tv  = books_1bc.groupby(["gstin",    "taxable_value"])["books_group_idx"].count().to_dict()
books_supp_tv   = books_1bc.groupby(["Supplier", "taxable_value"])["books_group_idx"].count().to_dict()
gstr2b_gstin_tv = gstr2b_1bc.groupby(["gstin",   "taxable_value"])["gstr2b_idx"].count().to_dict()
gstr2b_supp_tv  = gstr2b_1bc.groupby(["supplier","taxable_value"])["gstr2b_idx"].count().to_dict()

def _get_counts(row):
    if row["match_branch"] == "gstin":
        b = books_gstin_tv.get( (row["gstin"],    row["taxable_value_b"]), 1)
        g = gstr2b_gstin_tv.get((row["gstin"],    row["taxable_value_g"]), 1)
    else:
        b = books_supp_tv.get(  (row["Supplier"], row["taxable_value_b"]), 1)
        g = gstr2b_supp_tv.get( (row["supplier"], row["taxable_value_g"]), 1)
    return pd.Series({"b_count": b, "g_count": g})

cands_1bc[["b_count", "g_count"]] = cands_1bc.apply(_get_counts, axis=1)
cands_1bc["is_unique"] = (cands_1bc["b_count"] == 1) & (cands_1bc["g_count"] == 1)

# -------- 1B: unique candidates → greedy one-to-one auto-match --------
unique_1bc = cands_1bc[cands_1bc["is_unique"]].copy()
unique_1bc["total_money_diff"] = (
    (unique_1bc["taxable_value_b"] - unique_1bc["taxable_value_g"]).abs() +
    (unique_1bc["cgst_b"]          - unique_1bc["cgst_g"]).abs()          +
    (unique_1bc["sgst_b"]          - unique_1bc["sgst_g"]).abs()          +
    (unique_1bc["igst_b"]          - unique_1bc["igst_g"]).abs()
)
unique_1bc["date_diff_days"] = (
    unique_1bc["date_b"] - unique_1bc["date_g"]
).abs().dt.days.fillna(999999)

unique_1bc = unique_1bc.sort_values(
    by=["total_money_diff", "date_diff_days"], ascending=[True, True]
)

accepted_1b    = []
used_books_1b  = set()
used_gstr2b_1b = set()
rank_cols_1b   = ["total_money_diff", "date_diff_days"]

for bid, group in unique_1bc.groupby("books_group_idx", sort=False):
    avail = group[
        ~group["books_group_idx"].isin(used_books_1b) &
        ~group["gstr2b_idx"].isin(used_gstr2b_1b)
    ]
    if avail.empty:
        continue
    best = avail.iloc[0]
    tied = avail[(avail[rank_cols_1b] == best[rank_cols_1b]).all(axis=1)]
    if len(tied) > 1:
        continue  # genuine tie → leave in pool, falls through to Sheet 2/3
    accepted_1b.append(best)
    used_books_1b.add(best["books_group_idx"])
    used_gstr2b_1b.add(best["gstr2b_idx"])

sheet1b = pd.DataFrame(accepted_1b)
if not sheet1b.empty:
    sheet1b["flag"] = "invoice_differs"
    sheet1b["step"] = "sheet1b"

# -------- 1C: collision candidates → blue --------
sheet1c_blue = cands_1bc[~cands_1bc["is_unique"]].copy()
if not sheet1c_blue.empty:
    sheet1c_blue["flag"] = "blue"
    sheet1c_blue["step"] = "sheet1c"

# Update global pools (only 1B matches are consumed; 1C rows stay for Sheet 2/3)
used_1b_books  = set(sheet1b["books_group_idx"]) if not sheet1b.empty else set()
used_1b_gstr2b = set(sheet1b["gstr2b_idx"])      if not sheet1b.empty else set()

books_pool  = books_pool[~books_pool["books_group_idx"].isin(used_1b_books)].copy()
gstr2b_pool = gstr2b_pool[~gstr2b_pool["gstr2b_idx"].isin(used_1b_gstr2b)].copy()

print(f"Sheet 1B auto-matches:                {len(sheet1b)}")
print(f"Sheet 1C blue (collision candidates): {len(sheet1c_blue)}")
print(f"Books groups remaining: {len(books_pool)}")
print(f"2B remaining:           {len(gstr2b_pool)}")

Sheet 1B auto-matches:                15
Sheet 1C blue (collision candidates): 90
Books groups remaining: 175
2B remaining:           120

# **Sheet 2 — Standardized Invoice**

In [31]:
import re

def standardize_invoice(val):
    """Uppercase, strip spaces/slashes/hyphens, drop leading zeros."""
    if pd.isna(val) or str(val).strip() in ("", "<NA>", "nan"):
        return None
    s = re.sub(r"[\s/\-]+", "", str(val)).upper().lstrip("0")
    return s if s else None

books_pool2 = books_pool.copy()
gstr2b_pool2 = gstr2b_pool.copy()

books_pool2["std_voucher"] = books_pool2["Voucher Number"].apply(standardize_invoice)
gstr2b_pool2["std_invoice"] = gstr2b_pool2["invoice_number"].apply(standardize_invoice)

# Branch 1: GSTIN + std_invoice
merge2_gstin_invoice = books_pool2.merge(
    gstr2b_pool2,
    left_on=["gstin", "std_voucher"],
    right_on=["gstin", "std_invoice"],
    how="inner",
    suffixes=("_b", "_g")
)

# Branch 2: std_invoice + supplier
merge2_invoice_supplier = books_pool2.merge(
    gstr2b_pool2,
    left_on=["std_voucher", "Supplier"],
    right_on=["std_invoice", "supplier"],
    how="inner",
    suffixes=("_b", "_g")
)

sheet2_candidates = pd.concat(
    [merge2_gstin_invoice, merge2_invoice_supplier], ignore_index=True
).drop_duplicates(subset=["books_group_idx", "gstr2b_idx"])

# Money filter
taxable_match2 = abs(sheet2_candidates["taxable_value_b"] - sheet2_candidates["taxable_value_g"]) <= TOL
component_tax_match2 = (
    (abs(sheet2_candidates["cgst_b"] - sheet2_candidates["cgst_g"]) <= TOL) &
    (abs(sheet2_candidates["sgst_b"] - sheet2_candidates["sgst_g"]) <= TOL) &
    (abs(sheet2_candidates["igst_b"] - sheet2_candidates["igst_g"]) <= TOL)
)
total_tax_match2 = abs(
    (sheet2_candidates["cgst_b"] + sheet2_candidates["sgst_b"] + sheet2_candidates["igst_b"]) -
    (sheet2_candidates["cgst_g"] + sheet2_candidates["sgst_g"] + sheet2_candidates["igst_g"])
) <= TOL

sheet2_candidates = sheet2_candidates[
    taxable_match2 & (component_tax_match2 | total_tax_match2)
].copy()

# Ranking (same as Sheet 1A)
sheet2_candidates["invoice_exact"] = (
    sheet2_candidates["Voucher Number"] == sheet2_candidates["invoice_number"]
)
sheet2_candidates["gstin_exact"] = sheet2_candidates["gstin"].notna()
sheet2_candidates["supplier_exact"] = (
    sheet2_candidates["Supplier"] == sheet2_candidates["supplier"]
)
sheet2_candidates["total_money_diff"] = (
    (sheet2_candidates["taxable_value_b"] - sheet2_candidates["taxable_value_g"]).abs() +
    (sheet2_candidates["cgst_b"] - sheet2_candidates["cgst_g"]).abs() +
    (sheet2_candidates["sgst_b"] - sheet2_candidates["sgst_g"]).abs() +
    (sheet2_candidates["igst_b"] - sheet2_candidates["igst_g"]).abs()
)
sheet2_candidates["date_diff_days"] = (
    sheet2_candidates["date_b"] - sheet2_candidates["date_g"]
).abs().dt.days.fillna(999999)

complete_cols2 = ["gstin", "Voucher Number", "Supplier", "invoice_number", "supplier"]
sheet2_candidates["blank_count"] = sheet2_candidates[complete_cols2].isna().sum(axis=1)

sheet2_candidates = sheet2_candidates.sort_values(
    by=["invoice_exact", "gstin_exact", "supplier_exact", "total_money_diff", "date_diff_days", "blank_count"],
    ascending=[False, False, False, True, True, True]
)

accepted_rows2 = []
needs_review_sheet2 = []
used_books2 = set()
used_gstr2b2 = set()

rank_cols2 = ["invoice_exact", "gstin_exact", "supplier_exact", "total_money_diff", "date_diff_days", "blank_count"]

for books_id, group in sheet2_candidates.groupby("books_group_idx", sort=False):
    available = group[
        ~group["books_group_idx"].isin(used_books2) &
        ~group["gstr2b_idx"].isin(used_gstr2b2)
    ]
    if available.empty:
        continue
    best = available.iloc[0]
    tied_best = available[(available[rank_cols2] == best[rank_cols2]).all(axis=1)]
    if len(tied_best) > 1:
        needs_review_sheet2.append(tied_best)
        continue
    accepted_rows2.append(best)
    used_books2.add(best["books_group_idx"])
    used_gstr2b2.add(best["gstr2b_idx"])

sheet2 = pd.DataFrame(accepted_rows2)
needs_review_sheet2 = (
    pd.concat(needs_review_sheet2, ignore_index=True)
    if needs_review_sheet2 else
    pd.DataFrame(columns=sheet2_candidates.columns)
)

# Update global pools
books_pool = books_pool[~books_pool["books_group_idx"].isin(used_books2)].copy()
gstr2b_pool = gstr2b_pool[~gstr2b_pool["gstr2b_idx"].isin(used_gstr2b2)].copy()

print(f"Sheet 2 candidates: {len(sheet2_candidates)}")
print(f"Sheet 2 new matches: {len(sheet2)}")
print(f"Sheet 2 needs review ties: {len(needs_review_sheet2)}")
print(f"Books groups remaining: {len(books_pool)}")
print(f"2B remaining: {len(gstr2b_pool)}")

Sheet 2 candidates: 3
Sheet 2 new matches: 3
Sheet 2 needs review ties: 0
Books groups remaining: 172
2B remaining: 117

# **Sheet 3 — (GSTIN exact or Supplier exact) + fuzzy invoice + money**

In [32]:
from rapidfuzz import fuzz

FUZZY_THRESHOLD = 80  # % similarity on standardized invoice strings — tune if needed

# -------- SHEET 3 --------
# GSTIN exact OR supplier exact  +  fuzzy invoice  +  money
# Auto-match : fuzzy score >= threshold AND amount unique for that identity
# Blue       : money + identity match but invoice too different, OR collision

books_3  = books_pool.copy()
gstr2b_3 = gstr2b_pool.copy()
books_3["std_voucher"]  = books_3["Voucher Number"].apply(standardize_invoice)
gstr2b_3["std_invoice"] = gstr2b_3["invoice_number"].apply(standardize_invoice)

# Branch A: GSTIN exact
branch_3a = books_3.merge(gstr2b_3, on="gstin", how="inner", suffixes=("_b", "_g"))
branch_3a["match_branch"] = "gstin"

# Branch B: supplier exact
branch_3b = books_3.merge(
    gstr2b_3,
    left_on="Supplier", right_on="supplier",
    how="inner", suffixes=("_b", "_g")
)
branch_3b["match_branch"] = "supplier"
branch_3b["gstin"] = branch_3b["gstin_b"]   # normalize: gstin column always present after concat

cands_3 = pd.concat([branch_3a, branch_3b], ignore_index=True).drop_duplicates(
    subset=["books_group_idx", "gstr2b_idx"]
)

# Money filter
tv_ok   = abs(cands_3["taxable_value_b"] - cands_3["taxable_value_g"]) <= TOL
comp_ok = (
    (abs(cands_3["cgst_b"] - cands_3["cgst_g"]) <= TOL) &
    (abs(cands_3["sgst_b"] - cands_3["sgst_g"]) <= TOL) &
    (abs(cands_3["igst_b"] - cands_3["igst_g"]) <= TOL)
)
tot_ok  = abs(
    (cands_3["cgst_b"] + cands_3["sgst_b"] + cands_3["igst_b"]) -
    (cands_3["cgst_g"] + cands_3["sgst_g"] + cands_3["igst_g"])
) <= TOL
cands_3 = cands_3[tv_ok & (comp_ok | tot_ok)].copy()

# Drop exact invoice pairs — already handled by Sheets 1/2
inv_exact_3 = cands_3["Voucher Number"] == cands_3["invoice_number"]
std_exact_3 = (
    cands_3["std_voucher"].notna() &
    cands_3["std_invoice"].notna() &
    (cands_3["std_voucher"] == cands_3["std_invoice"])
)
cands_3 = cands_3[~(inv_exact_3 | std_exact_3)].copy()

# Fuzzy score on standardized invoice strings
def _fuzzy_inv(row):
    a, b = row["std_voucher"], row["std_invoice"]
    if not a or not b:
        return 0.0
    return fuzz.ratio(str(a), str(b))

cands_3["invoice_fuzzy_score"] = cands_3.apply(_fuzzy_inv, axis=1)

# Uniqueness check
books_gstin_tv_3  = books_3.groupby(["gstin",    "taxable_value"])["books_group_idx"].count().to_dict()
books_supp_tv_3   = books_3.groupby(["Supplier", "taxable_value"])["books_group_idx"].count().to_dict()
gstr2b_gstin_tv_3 = gstr2b_3.groupby(["gstin",   "taxable_value"])["gstr2b_idx"].count().to_dict()
gstr2b_supp_tv_3  = gstr2b_3.groupby(["supplier","taxable_value"])["gstr2b_idx"].count().to_dict()

def _counts_3(row):
    if row["match_branch"] == "gstin":
        b = books_gstin_tv_3.get( (row["gstin"],    row["taxable_value_b"]), 1)
        g = gstr2b_gstin_tv_3.get((row["gstin"],    row["taxable_value_g"]), 1)
    else:
        b = books_supp_tv_3.get(  (row["Supplier"], row["taxable_value_b"]), 1)
        g = gstr2b_supp_tv_3.get( (row["supplier"], row["taxable_value_g"]), 1)
    return pd.Series({"b_count": b, "g_count": g})

cands_3[["b_count", "g_count"]] = cands_3.apply(_counts_3, axis=1)
cands_3["is_unique"] = (cands_3["b_count"] == 1) & (cands_3["g_count"] == 1)

# Auto-match: fuzzy hit AND unique
auto_3 = cands_3[
    (cands_3["invoice_fuzzy_score"] >= FUZZY_THRESHOLD) & cands_3["is_unique"]
].copy()

auto_3["total_money_diff"] = (
    (auto_3["taxable_value_b"] - auto_3["taxable_value_g"]).abs() +
    (auto_3["cgst_b"]          - auto_3["cgst_g"]).abs()          +
    (auto_3["sgst_b"]          - auto_3["sgst_g"]).abs()          +
    (auto_3["igst_b"]          - auto_3["igst_g"]).abs()
)
auto_3["date_diff_days"] = (
    auto_3["date_b"] - auto_3["date_g"]
).abs().dt.days.fillna(999999)

auto_3 = auto_3.sort_values(
    by=["invoice_fuzzy_score", "total_money_diff", "date_diff_days"],
    ascending=[False, True, True]
)

# Greedy one-to-one selection
accepted_3    = []
used_books_3  = set()
used_gstr2b_3 = set()
rank_cols_3   = ["invoice_fuzzy_score", "total_money_diff", "date_diff_days"]

for bid, group in auto_3.groupby("books_group_idx", sort=False):
    avail = group[
        ~group["books_group_idx"].isin(used_books_3) &
        ~group["gstr2b_idx"].isin(used_gstr2b_3)
    ]
    if avail.empty:
        continue
    best = avail.iloc[0]
    tied = avail[(avail[rank_cols_3] == best[rank_cols_3]).all(axis=1)]
    if len(tied) > 1:
        continue  # genuine tie → falls through to Sheet 4/5
    accepted_3.append(best)
    used_books_3.add(best["books_group_idx"])
    used_gstr2b_3.add(best["gstr2b_idx"])

sheet3 = pd.DataFrame(accepted_3)
if not sheet3.empty:
    sheet3["flag"] = "invoice_fuzzy"
    sheet3["step"] = "sheet3"

# Blue: invoice too different (score < threshold) OR collision (amount not unique)
# Advisory only — pairs are NOT removed from pool; they flow to Sheet 4/5 still
sheet3_blue = cands_3[
    (cands_3["invoice_fuzzy_score"] < FUZZY_THRESHOLD) |
    (~cands_3["is_unique"])
].copy()
if not sheet3.empty:
    sheet3_blue = sheet3_blue[~sheet3_blue["gstr2b_idx"].isin(used_gstr2b_3)]
if not sheet3_blue.empty:
    sheet3_blue["flag"] = "blue"
    sheet3_blue["step"] = "sheet3"

# Update pools — only auto-matched rows consumed
books_pool  = books_pool[~books_pool["books_group_idx"].isin(used_books_3)].copy()
gstr2b_pool = gstr2b_pool[~gstr2b_pool["gstr2b_idx"].isin(used_gstr2b_3)].copy()

print(f"Sheet 3 auto-matches (fuzzy invoice): {len(sheet3)}")
print(f"Sheet 3 blue (review):                {len(sheet3_blue)}")
print(f"Books groups remaining: {len(books_pool)}")
print(f"2B remaining:           {len(gstr2b_pool)}")

Sheet 3 auto-matches (fuzzy invoice): 0
Sheet 3 blue (review):                90
Books groups remaining: 172
2B remaining:           117

In [33]:
from rapidfuzz import fuzz

SUPPLIER_FUZZY_THRESHOLD = 85  # % similarity on supplier name — tune if needed

# -------- SHEET 4 --------
# fuzzy supplier + fuzzy invoice + money
# Auto-match (proposal): both scores >= threshold AND amount unique
# Blue: fuzzy supplier matches but invoice too different, OR collision

books_4  = books_pool.copy()
gstr2b_4 = gstr2b_pool.copy()
books_4["std_voucher"]  = books_4["Voucher Number"].apply(standardize_invoice)
gstr2b_4["std_invoice"] = gstr2b_4["invoice_number"].apply(standardize_invoice)

# Cross-join on money tolerance — only keep pairs within ₹2 taxable value.
# Full cross-join is too large; pre-filter by taxable_value bucket first.
books_4["tv_round"] = books_4["taxable_value"].round(0)
gstr2b_4["tv_round"] = gstr2b_4["taxable_value"].round(0)

# Merge on rounded taxable value to limit candidate space, then money-filter properly
pre = books_4.merge(gstr2b_4, on="tv_round", how="inner", suffixes=("_b", "_g"))

tv_ok   = abs(pre["taxable_value_b"] - pre["taxable_value_g"]) <= TOL
comp_ok = (
    (abs(pre["cgst_b"] - pre["cgst_g"]) <= TOL) &
    (abs(pre["sgst_b"] - pre["sgst_g"]) <= TOL) &
    (abs(pre["igst_b"] - pre["igst_g"]) <= TOL)
)
tot_ok  = abs(
    (pre["cgst_b"] + pre["sgst_b"] + pre["igst_b"]) -
    (pre["cgst_g"] + pre["sgst_g"] + pre["igst_g"])
) <= TOL
cands_4 = pre[tv_ok & (comp_ok | tot_ok)].copy()

# Drop pairs where supplier is already exact (Sheet 3 would have caught those)
exact_supplier = cands_4["Supplier"] == cands_4["supplier"]
cands_4 = cands_4[~exact_supplier].copy()

# Drop invoice-exact pairs
inv_exact_4 = cands_4["Voucher Number"] == cands_4["invoice_number"]
std_exact_4 = (
    cands_4["std_voucher"].notna() &
    cands_4["std_invoice"].notna() &
    (cands_4["std_voucher"] == cands_4["std_invoice"])
)
cands_4 = cands_4[~(inv_exact_4 | std_exact_4)].copy()

# Compute fuzzy scores
def _scores_4(row):
    sup_score = fuzz.token_sort_ratio(str(row["Supplier"]), str(row["supplier"]))
    a, b = row["std_voucher"], row["std_invoice"]
    inv_score = fuzz.ratio(str(a), str(b)) if (a and b) else 0.0
    return pd.Series({"supplier_fuzzy_score": sup_score, "invoice_fuzzy_score": inv_score})

cands_4[["supplier_fuzzy_score", "invoice_fuzzy_score"]] = cands_4.apply(_scores_4, axis=1)

# Keep only rows where supplier is fuzzy-close enough to be worth considering
cands_4 = cands_4[cands_4["supplier_fuzzy_score"] >= SUPPLIER_FUZZY_THRESHOLD].copy()

# Uniqueness check (keyed on supplier name since no exact GSTIN join here)
books_supp_tv_4   = books_4.groupby(["Supplier", "taxable_value"])["books_group_idx"].count().to_dict()
gstr2b_supp_tv_4  = gstr2b_4.groupby(["supplier","taxable_value"])["gstr2b_idx"].count().to_dict()

def _counts_4(row):
    b = books_supp_tv_4.get( (row["Supplier"], row["taxable_value_b"]), 1)
    g = gstr2b_supp_tv_4.get((row["supplier"], row["taxable_value_g"]), 1)
    return pd.Series({"b_count": b, "g_count": g})

cands_4[["b_count", "g_count"]] = cands_4.apply(_counts_4, axis=1)
cands_4["is_unique"] = (cands_4["b_count"] == 1) & (cands_4["g_count"] == 1)

# Auto-match proposals: both fuzzy scores pass AND unique
auto_4 = cands_4[
    (cands_4["invoice_fuzzy_score"] >= FUZZY_THRESHOLD) & cands_4["is_unique"]
].copy()

auto_4["total_money_diff"] = (
    (auto_4["taxable_value_b"] - auto_4["taxable_value_g"]).abs() +
    (auto_4["cgst_b"]          - auto_4["cgst_g"]).abs()          +
    (auto_4["sgst_b"]          - auto_4["sgst_g"]).abs()          +
    (auto_4["igst_b"]          - auto_4["igst_g"]).abs()
)
auto_4["date_diff_days"] = (
    auto_4["date_b"] - auto_4["date_g"]
).abs().dt.days.fillna(999999)

auto_4 = auto_4.sort_values(
    by=["supplier_fuzzy_score", "invoice_fuzzy_score", "total_money_diff", "date_diff_days"],
    ascending=[False, False, True, True]
)

# Greedy one-to-one selection
accepted_4    = []
used_books_4  = set()
used_gstr2b_4 = set()
rank_cols_4   = ["supplier_fuzzy_score", "invoice_fuzzy_score", "total_money_diff", "date_diff_days"]

for bid, group in auto_4.groupby("books_group_idx", sort=False):
    avail = group[
        ~group["books_group_idx"].isin(used_books_4) &
        ~group["gstr2b_idx"].isin(used_gstr2b_4)
    ]
    if avail.empty:
        continue
    best = avail.iloc[0]
    tied = avail[(avail[rank_cols_4] == best[rank_cols_4]).all(axis=1)]
    if len(tied) > 1:
        continue  # genuine tie → Sheet 5 / unmatched
    accepted_4.append(best)
    used_books_4.add(best["books_group_idx"])
    used_gstr2b_4.add(best["gstr2b_idx"])

sheet4 = pd.DataFrame(accepted_4)
if not sheet4.empty:
    sheet4["flag"]  = "fuzzy_supplier_invoice"
    sheet4["step"]  = "sheet4"

# Blue: fuzzy supplier matches but invoice too different, OR collision
sheet4_blue = cands_4[
    (cands_4["invoice_fuzzy_score"] < FUZZY_THRESHOLD) |
    (~cands_4["is_unique"])
].copy()
if not sheet4.empty:
    sheet4_blue = sheet4_blue[~sheet4_blue["gstr2b_idx"].isin(used_gstr2b_4)]
if not sheet4_blue.empty:
    sheet4_blue["flag"] = "blue"
    sheet4_blue["step"] = "sheet4"

# Update pools
books_pool  = books_pool[~books_pool["books_group_idx"].isin(used_books_4)].copy()
gstr2b_pool = gstr2b_pool[~gstr2b_pool["gstr2b_idx"].isin(used_gstr2b_4)].copy()

print(f"Sheet 4 auto-matches (fuzzy supplier+invoice): {len(sheet4)}")
print(f"Sheet 4 blue (review):                         {len(sheet4_blue)}")
print(f"Books groups remaining: {len(books_pool)}")
print(f"2B remaining:           {len(gstr2b_pool)}")

Sheet 4 auto-matches (fuzzy supplier+invoice): 0
Sheet 4 blue (review):                         114
Books groups remaining: 172
2B remaining:           117

In [34]:
books_pool

,books_group_idx,group_key_type,group_key_1,group_key_2,Supplier,Voucher Number,gstin,date,taxable_value,cgst,sgst,igst,gross_total,source_rows,total_tax
1,1,gstin_invoice,07ALEPK3083E1ZB,2024-25/2178,KHURANA MOTORS,2024-25/2178,07ALEPK3083E1ZB,2025-02-11,26975.00,0.00,0.00,4855.5,31830.50,[551],4855.50
3,3,gstin_invoice,10FGTPK5221F1ZL,29,UPENDRA KUMAR KUSHWAHA,29,10FGTPK5221F1ZL,2025-02-01,160000.00,0.00,0.00,28800.0,188800.00,[537],28800.00
4,4,gstin_invoice,27AACFU8905A1ZC_X000D_,UCM/24-25/879,UCHAGAONKAR CONSTRUCTION MACHINERY_X000D_,UCM/24-25/879,27AACFU8905A1ZC_X000D_,2025-02-20,1999370.00,0.00,0.00,359886.6,2359256.60,[542],359886.60
5,5,gstin_invoice,27AAFCI1096N1Z4,1527,INNOVISION INFRASOL PRIVATE LTD_X000D_,1527,27AAFCI1096N1Z4,2025-02-01,80000.00,0.00,0.00,14400.0,94400.00,[545],14400.00
8,8,gstin_invoice,29AAACN4165C2ZM,67300031240100026180,THE NEW INDIA ASSURANCE CO. LTD,67300031240100026180,29AAACN4165C2ZM,2025-02-07,15128.00,1361.52,1361.52,0.0,17851.04,[437],2723.04
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
515,515,supplier_invoice,SHREE RAGHAVENDRA CRUSHER,215,SHREE RAGHAVENDRA CRUSHER,215,<NA>,2025-02-17,47132.50,1178.31,1178.31,0.0,49489.12,[221],2356.62
516,516,supplier_invoice,SHREE RAGHAVENDRA CRUSHER,216,SHREE RAGHAVENDRA CRUSHER,216,<NA>,2025-02-17,31165.25,779.13,779.13,0.0,32723.51,[222],1558.26
517,517,supplier_invoice,SHREE RAGHAVENDRA CRUSHER,219,SHREE RAGHAVENDRA CRUSHER,219,<NA>,2025-02-22,37227.55,930.69,930.69,0.0,39088.93,[244],1861.38
518,518,supplier_invoice,SHREE RAGHAVENDRA CRUSHER,220,SHREE RAGHAVENDRA CRUSHER,220,<NA>,2025-02-24,43116.25,1077.91,1077.91,0.0,45272.06,[256],2155.82
519,519,supplier_invoice,ZAKIR CRANE SERVICE,1602,ZAKIR CRANE SERVICE,1602,<NA>,2025-02-17,65000.00,5850.00,5850.00,0.0,76700.00,[514],11700.00

In [35]:
gstr2b_pool

,gstr2b_idx,gstin,supplier,invoice_number,Invoice Details_Invoice type,date,invoice_value,Place of supply,Supply Attract Reverse Charge,taxable_value,...,sgst,Tax Amount_Cess(₹),GSTR-1/IFF/GSTR-5 Period,GSTR-1/IFF/GSTR-5 Filing Date,ITC Availability,Reason,Applicable % of Tax Rate,Source,IRN,IRN Date
0,0,33AABCV3609C1ZU,VRL LOGISTICS LIMITED,2693198910,Regular,2025-06-02,2890.0,Karnataka,Yes,2890.00,...,0.00,0,Feb'25,11/03/2025,Yes,NaN,100%,NaN,NaN,NaN
1,1,33AABCV3609C1ZU,VRL LOGISTICS LIMITED,3247580610,Regular,NaT,490.0,Karnataka,Yes,490.00,...,0.00,0,Feb'25,11/03/2025,Yes,NaN,100%,NaN,NaN,NaN
3,3,29AAZPN5768K1ZF,SHRI SHANTESHWAR ENGINERING COMPNAY,SSE/2079/24-25,Regular,NaT,750.0,Karnataka,No,635.59,...,57.20,0,Feb'25,11/03/2025,Yes,NaN,100%,E-Invoice,35b64dae4bd14d18f58b09cf1298d5f26d65e79eb77a57...,24/02/2025
7,7,29BNKPM3318K1ZL,HI TECH EARTHMOVERS,17111,Regular,NaT,500.0,Karnataka,No,424.00,...,38.16,0,Feb'25,08/03/2025,Yes,NaN,100%,NaN,NaN,NaN
14,14,29MUCPS9397G1ZG,RUHAIL ENTERPRISE,2929,Regular,NaT,814.2,Karnataka,No,690.00,...,62.10,0,Feb'25,11/03/2025,Yes,NaN,100%,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
447,447,09AAACI1838D1ZU,M/S INFO EDGE INDIA LTD,NK09I0225/004498,Regular,2025-09-02,3894.0,Karnataka,No,3300.00,...,0.00,0,Feb'25,11/03/2025,Yes,NaN,100%,E-Invoice,f841f9104bb14ac2ba8c2bd2a0318bc72b60b3b158d1fd...,09/02/2025
448,448,09AAACI1838D1ZU,M/S INFO EDGE INDIA LTD,NK09I0225/013844,Regular,NaT,8761.5,Karnataka,No,7425.00,...,0.00,0,Feb'25,11/03/2025,Yes,NaN,100%,E-Invoice,8b742c1ff831cbbb2b6abdff7a1c9f834b35089d586bdf...,21/02/2025
455,455,36AABCA4938P1Z8,A AHMEDALLY & CO P LTD,24-25/15178,Regular,2025-11-02,594.0,Karnataka,No,503.30,...,0.00,0,Feb'25,11/03/2025,Yes,NaN,100%,NaN,NaN,NaN
456,456,36AABCA4938P1Z8,A AHMEDALLY & CO P LTD,24-25/15186,Regular,2025-11-02,287.0,Karnataka,No,242.84,...,0.00,0,Feb'25,11/03/2025,Yes,NaN,100%,NaN,NaN,NaN
458,458,29ALQPR4896J1ZW,ISHA HYDRO POWER,103,Regular,NaT,71278.0,Karnataka,No,57927.06,...,6675.47,0,Feb'25,07/03/2025,Yes,NaN,100%,NaN,NaN,NaN

In [36]:
import json
import asyncio
import os
import re
from openai import AsyncOpenAI
from dotenv import load_dotenv


# ======================================================================
# SHEET 5 — AI IDENTITY MATCH
# ======================================================================
# Purpose:
#   Catch hard cases that fuzzy string matching can't resolve.
#   Examples: "L&T" ↔ "LARSEN AND TOUBRO LIMITED", abbreviations,
#   brand vs legal name, transliterations.
#
# How it works:
#   1. Build candidate pairs where money already matches within ₹2
#   2. For each pair, ask the AI: "is this the same supplier?"
#   3. AI returns JSON: {likely_match, confidence, reason}
#   4. High-confidence results → proposals  (Sheet 6 finalises them)
#   5. Low-confidence results  → blue list  (human review)
#
# Design rules (design.md §5.5):
#   - temperature=0: deterministic, same input always gives same output
#   - Pre-filter first: AI never sees every-row-vs-every-row
#   - Log exact input AND output for every single call (audit trail)
#   - Confidence below threshold → blue, never auto-sealed
# ======================================================================
load_dotenv(r"d:\code_files\CA\GST_reconciliation\.env")
OPENROUTER_API_KEY = os.getenv("OPENROUTER_API_KEY")  # ← paste your key here
AI_MODEL           = "google/gemini-2.5-flash-lite"   # ← verify exact model ID on openrouter.ai/models
AI_CONF_THRESHOLD  = 0.85   # confidence >= this → proposal; below this → blue

# OpenAI-compatible client pointed at OpenRouter
client = AsyncOpenAI(
    base_url="https://openrouter.ai/api/v1",
    api_key=OPENROUTER_API_KEY,
)

TOL = 2

# -----------------------------------------------------------------------
# STEP 1: Build candidate pairs
# -----------------------------------------------------------------------
# We pre-filter by money BEFORE calling the AI.
# Merging on rounded taxable value limits the candidate space —
# the AI only ever sees pairs that are already close on money.

# Round taxable value to nearest rupee
books_5 = books_pool.copy()
gstr2b_5 = gstr2b_pool.copy()

books_5["tv_round"] = books_5["taxable_value"].round(0).astype("Int64")
gstr2b_5["tv_round"] = gstr2b_5["taxable_value"].round(0).astype("Int64")

# Expand each books row to nearby rounded buckets.
# Since TOL = 2, check current bucket plus +/- 2 rupees.
bucket_offsets = range(-TOL, TOL + 1)

books_5_expanded = books_5.loc[books_5.index.repeat(len(bucket_offsets))].copy()
books_5_expanded["tv_bucket"] = [
    tv + offset
    for tv in books_5["tv_round"]
    for offset in bucket_offsets
]

gstr2b_5["tv_bucket"] = gstr2b_5["tv_round"]

# Pre-join on nearby taxable-value buckets
pre_5 = books_5_expanded.merge(
    gstr2b_5,
    on="tv_bucket",
    how="inner",
    suffixes=("_b", "_g")
)

# Remove duplicates created by overlapping buckets
pre_5 = pre_5.drop_duplicates(
    subset=["books_group_idx", "gstr2b_idx"]
).copy()

# Now apply the actual strict design rule
tv_ok_5 = abs(pre_5["taxable_value_b"] - pre_5["taxable_value_g"]) <= TOL

comp_ok_5 = (
    (abs(pre_5["cgst_b"] - pre_5["cgst_g"]) <= TOL) &
    (abs(pre_5["sgst_b"] - pre_5["sgst_g"]) <= TOL) &
    (abs(pre_5["igst_b"] - pre_5["igst_g"]) <= TOL)
)

tot_ok_5 = abs(
    (pre_5["cgst_b"] + pre_5["sgst_b"] + pre_5["igst_b"]) -
    (pre_5["cgst_g"] + pre_5["sgst_g"] + pre_5["igst_g"])
) <= TOL

cands_5 = pre_5[tv_ok_5 & (comp_ok_5 | tot_ok_5)].copy()

print(f"Sheet 5 — candidate pairs to send to AI: {len(cands_5)}")

# -----------------------------------------------------------------------
# STEP 2: System prompt
# -----------------------------------------------------------------------
# We tell the model exactly what to return so we can parse it reliably.
# Strict JSON-only output. No markdown, no explanation outside the JSON.

SYSTEM_PROMPT = (
    "You are a GST reconciliation assistant for Indian businesses.\n\n"
    "You receive one possible invoice pair: one record from internal books and one record from GSTR-2B.\n"
    "Your job is to decide whether they are likely the SAME real-world invoice/supplier pair.\n\n"

    "IMPORTANT MATCHING PRINCIPLE:\n"
    "- Money is a hard gate: if taxable_diff or all tax differences are clearly outside tolerance, return no-match.\n"
    "- Money matching alone is NOT enough to match.\n"
    "- There must also be identity support from supplier name, invoice number, GST/business identity clues, or a strong abbreviation/legal-name relationship.\n"
    "- When uncertain, return no-match. A missed match is safer than a wrong match.\n\n"

    "FINANCIAL RULES:\n"
    "- Differences of 0, 1, or 2 rupees are acceptable rounding differences.\n"
    "- Small differences in CGST/SGST/IGST may be acceptable if total tax appears effectively the same.\n"
    "- If money differences are large or inconsistent, return likely_match=false even if names look similar.\n"
    "- Never use matching money by itself as the reason for a match.\n\n"

    "INVOICE NUMBER RULES:\n"
    "- Exact invoice number match is strong evidence.\n"
    "- Standardized invoice match is strong evidence: ignore spaces, hyphens, slashes, case, and leading zeros.\n"
    "- Prefix/suffix differences can still match when the rest is clearly the same, e.g. SPL-892 vs MSPL-892, FY/24-25/946 vs 946.\n"
    "- Internal voucher numbers may look completely different from the supplier invoice number; in that case supplier identity and money must be very strong.\n"
    "- If invoice numbers are different and supplier identity is weak, return no-match or low confidence.\n\n"

    "SUPPLIER NAME RULES — WHEN TO MATCH:\n"
    "- Known abbreviations or acronyms: L&T = Larsen and Toubro, HUL = Hindustan Unilever.\n"
    "- Only formatting differs: M/S prefix, Limited/Ltd suffix, & vs and, hyphen vs space, extra spaces.\n"
    "- Minor singular/plural variation: Hardware vs Hardwares.\n"
    "- Clear typo where the rest of the name is identical.\n"
    "- Transliteration variation of the same name: Sri vs Shri.\n"
    "- Bank entries: books may record a bank as 'KBL OD 0777000100021201' while GSTR-2B has 'KARNATAKA BANK LIMITED'. "
    "Known bank abbreviations include SBI, KBL, HDFC, ICICI, AXIS, BOI, PNB, BOB, CANARA, KOTAK, YES, IDFC, IOB, UCO, UBI.\n\n"

    "SUPPLIER NAME RULES — WHEN NOT TO MATCH:\n"
    "- Business-type word differs: TYRES vs MOTORS, ELECTRICALS vs PLYWOOD, STEEL vs CEMENT.\n"
    "- Short generic initials alone are not enough: NK, SR, RK with different suffixes.\n"
    "- Personal names with one-letter difference and no other support: SONA vs SOMA.\n"
    "- Common first word followed by different entity words: Akshaya Traders vs Akshaya Cement.\n\n"

    "CONFIDENCE GUIDANCE:\n"
    "- 0.95-1.00: supplier identity is clearly same and invoice/money also support it.\n"
    "- 0.85-0.94: strong likely match, minor invoice/name formatting issue.\n"
    "- 0.60-0.84: possible match but needs human review.\n"
    "- below 0.60: weak or unsafe match.\n\n"

    "Respond ONLY with valid JSON, no extra text, no markdown:\n"
    '{"likely_match": true or false, "confidence": 0.0 to 1.0, "reason": "one short sentence"}'

    "\n\nEXAMPLE OUTPUTS:\n"
    'For a confident match:\n'
    '{"likely_match": true, "confidence": 0.92, "reason": "Supplier abbreviation matches the legal name and invoice number is a close variant."}\n'
    'For a possible but unsafe match:\n'
    '{"likely_match": true, "confidence": 0.72, "reason": "Money matches and supplier names look related, but invoice numbers differ significantly."}\n'
    'For a no-match:\n'
    '{"likely_match": false, "confidence": 0.18, "reason": "Supplier business type and invoice number do not support the same entity."}\n\n'
    "Now respond ONLY with one valid JSON object for the given input."
)
# -----------------------------------------------------------------------
# STEP 3: AI call function
# -----------------------------------------------------------------------

def clean_supplier_name(name):
    # Remove Excel carriage-return artifacts (_x000D_, _X000D_)
    name = re.sub(r'_[xX]000[dD]_', '', str(name))
    # Remove actual newlines and carriage returns
    name = name.replace('\r', '').replace('\n', '').strip()
    return name

async def ask_ai_sheet5(sem, row):
    async with sem:
        payload = {
            "books_supplier":  clean_supplier_name(str(row["Supplier"])),
            "2b_supplier":     clean_supplier_name(str(row["supplier"])),
            "books_invoice":   str(row["Voucher Number"]),
            "2b_invoice":      str(row["invoice_number"]),
            "taxable_diff":    round(float(row["taxable_value_b"] - row["taxable_value_g"]), 2),
            "cgst_diff":       round(float(row["cgst_b"]          - row["cgst_g"]),          2),
            "sgst_diff":       round(float(row["sgst_b"]          - row["sgst_g"]),          2),
            "igst_diff":       round(float(row["igst_b"]          - row["igst_g"]),          2),
        }
        user_content = json.dumps(payload, ensure_ascii=False)

        try:
            response = await client.chat.completions.create(
                model=AI_MODEL,
                messages=[
                    {"role": "system", "content": SYSTEM_PROMPT},
                    {"role": "user",   "content": user_content},
                ],
                temperature=0,
            )

            raw = response.choices[0].message.content.strip()
            clean = re.sub(r"^```[a-z]*\n?", "", raw).rstrip("` \n")
            clean = re.sub(r'[\x00-\x1f\x7f]', ' ', clean)

            try:
                parsed = json.loads(clean)
            except json.JSONDecodeError:
                m = re.search(r'\{.*?\}', clean, re.DOTALL)
                if m:
                    parsed = json.loads(m.group())
                else:
                    raise

            result = {
                "likely_match": bool(parsed.get("likely_match", False)),
                "confidence":   float(parsed.get("confidence", 0.0)),
                "reason":       str(parsed.get("reason", "")),
                "ai_input":     user_content,
                "raw_response": raw,
                "error":        None,
            }

        except Exception as e:
            result = {
                "likely_match": False,
                "confidence":   0.0,
                "reason":       "",
                "ai_input":     user_content,
                "raw_response": "",
                "error":        str(e),
            }

        return {**row.to_dict(), **result}



# -----------------------------------------------------------------------
# STEP 4: Run AI on every candidate pair
# -----------------------------------------------------------------------

sem = asyncio.Semaphore(10)
tasks = [ask_ai_sheet5(sem, row) for _, row in cands_5.iterrows()]

print(f"Sending {len(tasks)} pairs to AI (10 concurrent)...")
ai_results = await asyncio.gather(*tasks)
print("Done.")



# -----------------------------------------------------------------------
# STEP 5: Split results into proposals / blue / no-match
# -----------------------------------------------------------------------
# Sheet 5 does NOT consume rows from the pool here.
# It only produces proposals. Sheet 6 does the final greedy one-to-one merge.

sheet5_all = pd.DataFrame(ai_results)
sheet5_all["step"] = "sheet5_ai"

# High-confidence positive → proposal for Sheet 6 to accept
sheet5_proposals = sheet5_all[
    sheet5_all["likely_match"] & (sheet5_all["confidence"] >= AI_CONF_THRESHOLD)
].copy()
sheet5_proposals["flag"] = "ai_match"

# Low-confidence positive → human should confirm before we seal it
sheet5_blue = sheet5_all[
    sheet5_all["likely_match"] & (sheet5_all["confidence"] < AI_CONF_THRESHOLD)
].copy()
sheet5_blue["flag"] = "blue"

# AI said no → stays in unmatched pool, Sheet 6 will list it
sheet5_no_match = sheet5_all[~sheet5_all["likely_match"]].copy()

# Any API errors — print so you can diagnose (wrong key, wrong model name, etc.)
sheet5_errors = sheet5_all[sheet5_all["error"].notna()].copy()

print(f"\nSheet 5 results:")
print(f"  Proposals (confident AI match): {len(sheet5_proposals)}")
print(f"  Blue (low confidence):          {len(sheet5_blue)}")
print(f"  No match:                       {len(sheet5_no_match)}")
if len(sheet5_errors) > 0:
    print(f"\n  ⚠ Errors ({len(sheet5_errors)} calls failed) — check API key / model ID:")
    print(sheet5_errors[["Supplier", "supplier", "error"]].to_string())

Sheet 5 — candidate pairs to send to AI: 125
Sending 125 pairs to AI (10 concurrent)...
Done.

Sheet 5 results:
  Proposals (confident AI match): 107
  Blue (low confidence):          0
  No match:                       18

In [37]:
sheet5_all.columns

Index(['books_group_idx', 'group_key_type', 'group_key_1', 'group_key_2',
       'Supplier', 'Voucher Number', 'gstin_b', 'date_b', 'taxable_value_b',
       'cgst_b', 'sgst_b', 'igst_b', 'gross_total', 'source_rows', 'total_tax',
       'tv_round_b', 'tv_bucket', 'gstr2b_idx', 'gstin_g', 'supplier',
       'invoice_number', 'Invoice Details_Invoice type', 'date_g',
       'invoice_value', 'Place of supply', 'Supply Attract Reverse Charge',
       'taxable_value_g', 'igst_g', 'cgst_g', 'sgst_g', 'Tax Amount_Cess(₹)',
       'GSTR-1/IFF/GSTR-5 Period', 'GSTR-1/IFF/GSTR-5 Filing Date',
       'ITC Availability', 'Reason', 'Applicable % of Tax Rate', 'Source',
       'IRN', 'IRN Date', 'tv_round_g', 'likely_match', 'confidence', 'reason',
       'ai_input', 'raw_response', 'error', 'step'],
      dtype='str')

In [38]:
sheet5_all[["Supplier", "supplier", "Voucher Number", "invoice_number", "likely_match", "confidence", "reason"]].head(50)

,Supplier,supplier,Voucher Number,invoice_number,likely_match,confidence,reason
0,UPENDRA KUMAR KUSHWAHA,ARUNKUMAR RATHOD,29,152,False,0.10,Supplier names are completely different and in...
1,UCHAGAONKAR CONSTRUCTION MACHINERY_X000D_,UCHGAONKAR CONSTRUCTION MACHINERY,UCM/24-25/879,UCM/24-25/879,True,0.98,Supplier names are a very close variant with a...
2,THE NEW INDIA ASSURANCE CO. LTD,THE NEW INDIA ASSURANCE COMPANY LIMITED,67300031241100026859,67300024E0034619,True,0.95,Supplier names are a clear match with only min...
3,THE NEW INDIA ASSURANCE CO. LTD,THE NEW INDIA ASSURANCE COMPANY LIMITED,67300031241100026859,67300024E0034620,True,0.90,Supplier names are a close match with minor fo...
4,THE NEW INDIA ASSURANCE CO. LTD,THE NEW INDIA ASSURANCE COMPANY LIMITED,67300031241100026859,67300024E0034621,True,0.95,Supplier names are identical with only minor f...
5,THE NEW INDIA ASSURANCE CO. LTD,THE NEW INDIA ASSURANCE COMPANY LIMITED,67300031241100026860,67300024E0034619,True,0.90,Supplier names are a close match with minor fo...
6,THE NEW INDIA ASSURANCE CO. LTD,THE NEW INDIA ASSURANCE COMPANY LIMITED,67300031241100026860,67300024E0034620,True,0.95,Supplier names are identical with minor format...
7,THE NEW INDIA ASSURANCE CO. LTD,THE NEW INDIA ASSURANCE COMPANY LIMITED,67300031241100026860,67300024E0034621,True,0.90,Supplier names are a close match with minor fo...
8,THE NEW INDIA ASSURANCE CO. LTD,THE NEW INDIA ASSURANCE COMPANY LIMITED,67300031241100026861,67300024E0034619,True,0.90,Supplier names are a close match with minor fo...
9,THE NEW INDIA ASSURANCE CO. LTD,THE NEW INDIA ASSURANCE COMPANY LIMITED,67300031241100026861,67300024E0034620,True,0.95,Supplier names are identical with minor format...
10,THE NEW INDIA ASSURANCE CO. LTD,THE NEW INDIA ASSURANCE COMPANY LIMITED,67300031241100026861,67300024E0034621,True,0.90,Supplier names are a close match with minor fo...
11,THE NEW INDIA ASSURANCE CO. LTD,THE NEW INDIA ASSURANCE COMPANY LIMITED,67300031241300026242,67300024E0033815,True,0.95,Supplier names are a close match with only min...
12,THE NEW INDIA ASSURANCE CO. LTD,THE NEW INDIA ASSURANCE COMPANY LIMITED,67300031241300026242,67300024E0033816,True,0.95,Supplier names are a close match with minor fo...
13,THE NEW INDIA ASSURANCE CO. LTD,THE NEW INDIA ASSURANCE COMPANY LIMITED,67300031241300026242,67300024E0034586,False,0.35,"Supplier names are very similar, but invoice n..."
14,THE NEW INDIA ASSURANCE CO. LTD,THE NEW INDIA ASSURANCE COMPANY LIMITED,67300031241300026242,67300024E0034590,False,0.35,"Supplier names are very similar, but invoice n..."
15,THE NEW INDIA ASSURANCE CO. LTD,THE NEW INDIA ASSURANCE COMPANY LIMITED,67300031241300026242,67300024E0034591,True,0.95,Supplier names are identical with minor format...
16,THE NEW INDIA ASSURANCE CO. LTD,THE NEW INDIA ASSURANCE COMPANY LIMITED,67300031241300026242,67300024E0034592,True,0.95,Supplier names are identical with minor format...
17,THE NEW INDIA ASSURANCE CO. LTD,THE NEW INDIA ASSURANCE COMPANY LIMITED,67300031241300026242,67300024E0034593,True,0.95,Supplier names are identical with minor format...
18,THE NEW INDIA ASSURANCE CO. LTD,THE NEW INDIA ASSURANCE COMPANY LIMITED,67300031241300026242,67300024E0034599,False,0.35,"Supplier names are very similar, but invoice n..."
19,THE NEW INDIA ASSURANCE CO. LTD,THE NEW INDIA ASSURANCE COMPANY LIMITED,67300031241300026242,67300024E0034618,False,0.35,"Supplier names are very similar, but invoice n..."
20,THE NEW INDIA ASSURANCE CO. LTD,THE NEW INDIA ASSURANCE COMPANY LIMITED,67300031241300026243,67300024E0033815,True,0.95,Supplier names are identical with minor format...
21,THE NEW INDIA ASSURANCE CO. LTD,THE NEW INDIA ASSURANCE COMPANY LIMITED,67300031241300026243,67300024E0033816,True,0.95,Supplier names are identical with minor format...
22,THE NEW INDIA ASSURANCE CO. LTD,THE NEW INDIA ASSURANCE COMPANY LIMITED,67300031241300026243,67300024E0034586,False,0.45,"Supplier names are very similar, but invoice n..."
23,THE NEW INDIA ASSURANCE CO. LTD,THE NEW INDIA ASSURANCE COMPANY LIMITED,67300031241300026243,67300024E0034590,False,0.35,"Supplier names are very similar, but invoice n..."
24,THE NEW INDIA ASSURANCE CO. LTD,THE NEW INDIA ASSURANCE COMPANY LIMITED,67300031241300026243,67300024E0034591,True,0.95,Supplier names are a close match with only min...
25,THE NEW INDIA ASSURANCE CO. LTD,THE NEW INDIA ASSURANCE COMPANY LIMITED,67300031241300026243,67300024E0034592,True,0.95,Supplier names are a close match with only min...
26,THE NEW INDIA ASSURANCE CO. LTD,THE NEW INDIA ASSURANCE COMPANY LIMITED,67300031241300026243,67300024E0034593,True,0.95,Supplier names are identical with minor format...
27,THE NEW INDIA ASSURANCE CO. LTD,THE NEW INDIA ASSURANCE COMPANY LIMITED,67300031241300026243,67300024E0034599,True,0.95,Supplier names are identical with minor format...
28,THE NEW INDIA ASSURANCE CO. LTD,THE NEW INDIA ASSURANCE COMPANY LIMITED,67300031241300026243,67300024E0034618,True,0.95,Supplier names are identical with minor format...
29,THE NEW INDIA ASSURANCE CO. LTD,THE NEW INDIA ASSURANCE COMPANY LIMITED,67300031241300026829,67300024E0033815,True,0.95,Supplier names are a clear match with only min...
30,THE NEW INDIA ASSURANCE CO. LTD,THE NEW INDIA ASSURANCE COMPANY LIMITED,67300031241300026829,67300024E0033816,True,0.95,Supplier names are a close match with only min...
31,THE NEW INDIA ASSURANCE CO. LTD,THE NEW INDIA ASSURANCE COMPANY LIMITED,67300031241300026829,67300024E0034586,True,0.95,Supplier names are identical with minor format...
32,THE NEW INDIA ASSURANCE CO. LTD,THE NEW INDIA ASSURANCE COMPANY LIMITED,67300031241300026829,67300024E0034590,True,0.95,Supplier names are identical with minor format...
33,THE NEW INDIA ASSURANCE CO. LTD,THE NEW INDIA ASSURANCE COMPANY LIMITED,67300031241300026829,67300024E0034591,True,0.95,Supplier names are identical with minor format...
34,THE NEW INDIA ASSURANCE CO. LTD,THE NEW INDIA ASSURANCE COMPANY LIMITED,67300031241300026829,67300024E0034592,False,0.45,"Supplier names are very similar, but invoice n..."
35,THE NEW INDIA ASSURANCE CO. LTD,THE NEW INDIA ASSURANCE COMPANY LIMITED,67300031241300026829,67300024E0034593,True,0.95,Supplier names are identical with minor format...
36,THE NEW INDIA ASSURANCE CO. LTD,THE NEW INDIA ASSURANCE COMPANY LIMITED,67300031241300026829,67300024E0034599,False,0.35,"Supplier names are very similar, but invoice n..."
37,THE NEW INDIA ASSURANCE CO. LTD,THE NEW INDIA ASSURANCE COMPANY LIMITED,67300031241300026829,67300024E0034618,True,0.95,Supplier names are identical with minor format...
38,THE NEW INDIA ASSURANCE CO. LTD,THE NEW INDIA ASSURANCE COMPANY LIMITED,67300031241300026833,67300024E0033815,True,0.95,Supplier names are a close match with only min...
39,THE NEW INDIA ASSURANCE CO. LTD,THE NEW INDIA ASSURANCE COMPANY LIMITED,67300031241300026833,67300024E0033816,True,0.95,Supplier names are identical with minor format...
40,THE NEW INDIA ASSURANCE CO. LTD,THE NEW INDIA ASSURANCE COMPANY LIMITED,67300031241300026833,67300024E0034586,True,0.95,Supplier names are a close match with minor fo...
41,THE NEW INDIA ASSURANCE CO. LTD,THE NEW INDIA ASSURANCE COMPANY LIMITED,67300031241300026833,67300024E0034590,True,0.95,Supplier names are a close match with only min...
42,THE NEW INDIA ASSURANCE CO. LTD,THE NEW INDIA ASSURANCE COMPANY LIMITED,67300031241300026833,67300024E0034591,True,0.95,Supplier names are a close match with only min...
43,THE NEW INDIA ASSURANCE CO. LTD,THE NEW INDIA ASSURANCE COMPANY LIMITED,67300031241300026833,67300024E0034592,True,0.95,Supplier names are a close match with minor fo...
44,THE NEW INDIA ASSURANCE CO. LTD,THE NEW INDIA ASSURANCE COMPANY LIMITED,67300031241300026833,67300024E0034593,True,0.95,Supplier names are a close match with only min...
45,THE NEW INDIA ASSURANCE CO. LTD,THE NEW INDIA ASSURANCE COMPANY LIMITED,67300031241300026833,67300024E0034599,False,0.35,"Supplier names are very similar, but invoice n..."
46,THE NEW INDIA ASSURANCE CO. LTD,THE NEW INDIA ASSURANCE COMPANY LIMITED,67300031241300026833,67300024E0034618,True,0.95,Supplier names are a close match with only min...
47,THE NEW INDIA ASSURANCE CO. LTD,THE NEW INDIA ASSURANCE COMPANY LIMITED,67300031241300026834,67300024E0033815,True,0.95,Supplier names are identical with minor format...
48,THE NEW INDIA ASSURANCE CO. LTD,THE NEW INDIA ASSURANCE COMPANY LIMITED,67300031241300026834,67300024E0033816,True,0.95,Supplier names are a close match with only min...
49,THE NEW INDIA ASSURANCE CO. LTD,THE NEW INDIA ASSURANCE COMPANY LIMITED,67300031241300026834,67300024E0034586,True,0.95,Supplier names are identical with minor format...

In [39]:
sheet5_all['likely_match'].value_counts()

likely_match
True     107
False     18
Name: count, dtype: int64